//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cora.CommIss.Iss.DoveraPoistenecClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OverPoistencaVstup", Namespace="http://b2b.dovera.sk")]
    [System.SerializableAttribute()]
    public partial class OverPoistencaVstup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Cora.CommIss.Iss.DoveraPoistenecClient.APITokenPouzivatela TokenPouzivatelaField;
        
        private string RCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ICPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Cora.CommIss.Iss.DoveraPoistenecClient.APITokenPouzivatela TokenPouzivatela {
            get {
                return this.TokenPouzivatelaField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenPouzivatelaField, value) != true)) {
                    this.TokenPouzivatelaField = value;
                    this.RaisePropertyChanged("TokenPouzivatela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string RC {
            get {
                return this.RCField;
            }
            set {
                if ((object.ReferenceEquals(this.RCField, value) != true)) {
                    this.RCField = value;
                    this.RaisePropertyChanged("RC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ICP {
            get {
                return this.ICPField;
            }
            set {
                if ((object.ReferenceEquals(this.ICPField, value) != true)) {
                    this.ICPField = value;
                    this.RaisePropertyChanged("ICP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Datum {
            get {
                return this.DatumField;
            }
            set {
                if ((object.ReferenceEquals(this.DatumField, value) != true)) {
                    this.DatumField = value;
                    this.RaisePropertyChanged("Datum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APITokenPouzivatela", Namespace="http://b2b.dovera.sk")]
    [System.SerializableAttribute()]
    public partial class APITokenPouzivatela : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string LoginField;
        
        private string DodavatelSWField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodNZField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodVZField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnikatnyKodPLAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CasovyLimitVolaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ICOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string DodavatelSW {
            get {
                return this.DodavatelSWField;
            }
            set {
                if ((object.ReferenceEquals(this.DodavatelSWField, value) != true)) {
                    this.DodavatelSWField = value;
                    this.RaisePropertyChanged("DodavatelSW");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string KodNZ {
            get {
                return this.KodNZField;
            }
            set {
                if ((object.ReferenceEquals(this.KodNZField, value) != true)) {
                    this.KodNZField = value;
                    this.RaisePropertyChanged("KodNZ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string KodVZ {
            get {
                return this.KodVZField;
            }
            set {
                if ((object.ReferenceEquals(this.KodVZField, value) != true)) {
                    this.KodVZField = value;
                    this.RaisePropertyChanged("KodVZ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string VS {
            get {
                return this.VSField;
            }
            set {
                if ((object.ReferenceEquals(this.VSField, value) != true)) {
                    this.VSField = value;
                    this.RaisePropertyChanged("VS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string UnikatnyKodPLA {
            get {
                return this.UnikatnyKodPLAField;
            }
            set {
                if ((object.ReferenceEquals(this.UnikatnyKodPLAField, value) != true)) {
                    this.UnikatnyKodPLAField = value;
                    this.RaisePropertyChanged("UnikatnyKodPLA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int CasovyLimitVolania {
            get {
                return this.CasovyLimitVolaniaField;
            }
            set {
                if ((this.CasovyLimitVolaniaField.Equals(value) != true)) {
                    this.CasovyLimitVolaniaField = value;
                    this.RaisePropertyChanged("CasovyLimitVolania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ICO {
            get {
                return this.ICOField;
            }
            set {
                if ((object.ReferenceEquals(this.ICOField, value) != true)) {
                    this.ICOField = value;
                    this.RaisePropertyChanged("ICO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OverPoistencaVystup", Namespace="http://b2b.dovera.sk")]
    [System.SerializableAttribute()]
    public partial class OverPoistencaVystup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Cora.CommIss.Iss.DoveraPoistenecClient.APIPoistnyVztahPoistenca PoistnyVztahPoistencaField;
        
        private bool JeNeplaticField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZaciatokEUPoisteniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MaNarokNaOdkladnuZSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Cora.CommIss.Iss.DoveraPoistenecClient.APIPoistnyVztahPoistenca PoistnyVztahPoistenca {
            get {
                return this.PoistnyVztahPoistencaField;
            }
            set {
                if ((this.PoistnyVztahPoistencaField.Equals(value) != true)) {
                    this.PoistnyVztahPoistencaField = value;
                    this.RaisePropertyChanged("PoistnyVztahPoistenca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool JeNeplatic {
            get {
                return this.JeNeplaticField;
            }
            set {
                if ((this.JeNeplaticField.Equals(value) != true)) {
                    this.JeNeplaticField = value;
                    this.RaisePropertyChanged("JeNeplatic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ZaciatokEUPoistenia {
            get {
                return this.ZaciatokEUPoisteniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ZaciatokEUPoisteniaField, value) != true)) {
                    this.ZaciatokEUPoisteniaField = value;
                    this.RaisePropertyChanged("ZaciatokEUPoistenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool MaNarokNaOdkladnuZS {
            get {
                return this.MaNarokNaOdkladnuZSField;
            }
            set {
                if ((this.MaNarokNaOdkladnuZSField.Equals(value) != true)) {
                    this.MaNarokNaOdkladnuZSField = value;
                    this.RaisePropertyChanged("MaNarokNaOdkladnuZS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIPoistnyVztahPoistenca", Namespace="http://schemas.dovera.sk/b2b/types")]
    public enum APIPoistnyVztahPoistenca : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NieJePoistencom = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JePoistencom = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JePoistencomEU = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://b2b.dovera.sk", ConfigurationName="DoveraPoistenecClient.PoistenecServiceSoap")]
    public interface PoistenecServiceSoap {
        
        // CODEGEN: Generating message contract since element name Vstup from namespace http://b2b.dovera.sk is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.Poistenec.OverPoistenca", ReplyAction="*")]
        Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaResponse OverPoistenca(Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.Poistenec.OverPoistenca", ReplyAction="*")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaResponse> OverPoistencaAsync(Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OverPoistencaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OverPoistenca", Namespace="http://b2b.dovera.sk", Order=0)]
        public Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaRequestBody Body;
        
        public OverPoistencaRequest() {
        }
        
        public OverPoistencaRequest(Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class OverPoistencaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaVstup Vstup;
        
        public OverPoistencaRequestBody() {
        }
        
        public OverPoistencaRequestBody(Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaVstup Vstup) {
            this.Vstup = Vstup;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OverPoistencaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OverPoistencaResponse", Namespace="http://b2b.dovera.sk", Order=0)]
        public Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaResponseBody Body;
        
        public OverPoistencaResponse() {
        }
        
        public OverPoistencaResponse(Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class OverPoistencaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaVystup Vystup;
        
        public OverPoistencaResponseBody() {
        }
        
        public OverPoistencaResponseBody(Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaVystup Vystup) {
            this.Vystup = Vystup;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PoistenecServiceSoapChannel : Cora.CommIss.Iss.DoveraPoistenecClient.PoistenecServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PoistenecServiceSoapClient : System.ServiceModel.ClientBase<Cora.CommIss.Iss.DoveraPoistenecClient.PoistenecServiceSoap>, Cora.CommIss.Iss.DoveraPoistenecClient.PoistenecServiceSoap {
        
        public PoistenecServiceSoapClient() {
        }
        
        public PoistenecServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PoistenecServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PoistenecServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PoistenecServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaResponse Cora.CommIss.Iss.DoveraPoistenecClient.PoistenecServiceSoap.OverPoistenca(Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaRequest request) {
            return base.Channel.OverPoistenca(request);
        }
        
        public Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaVystup OverPoistenca(Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaVstup Vstup) {
            Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaRequest inValue = new Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaRequest();
            inValue.Body = new Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaRequestBody();
            inValue.Body.Vstup = Vstup;
            Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaResponse retVal = ((Cora.CommIss.Iss.DoveraPoistenecClient.PoistenecServiceSoap)(this)).OverPoistenca(inValue);
            return retVal.Body.Vystup;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaResponse> Cora.CommIss.Iss.DoveraPoistenecClient.PoistenecServiceSoap.OverPoistencaAsync(Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaRequest request) {
            return base.Channel.OverPoistencaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaResponse> OverPoistencaAsync(Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaVstup Vstup) {
            Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaRequest inValue = new Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaRequest();
            inValue.Body = new Cora.CommIss.Iss.DoveraPoistenecClient.OverPoistencaRequestBody();
            inValue.Body.Vstup = Vstup;
            return ((Cora.CommIss.Iss.DoveraPoistenecClient.PoistenecServiceSoap)(this)).OverPoistencaAsync(inValue);
        }
    }
}
