// Generated by NATeC ClassGenerator v. 4.2.2014.502
// Source model: D:\svnroot\proj\Portal_ISS\extra\2016.4.0\Analyzy a davky\HD 44497\NE_HD44497_upravene.pdm
// Please do not edit this file - for custom additions to this class use a separate *$cust.cs file instead.
// Class Options: IMMUTABLE NOARCHIVE

using System;
using System.Data;
using Cora.Data.DBProvider;
using Cora.Natec.Base;

namespace Cora.CoraApp.ISS.EXT.MAT
{
	/// <summary>
	/// MET_DN_POZ (business trieda).
	/// </summary>
	[Serializable]
	public partial class CdoMET_DN_POZ : clsDataObjR
	{
		#region Properties

		/// <summary>
		/// Vráti primárny kľúč.
		/// </summary>
		/// <value>Primárny kľúč.</value>
		public override long iPK
		{
			get
			{
				return _col_IId;
			}
			set
			{
				_col_IId = (int)value;
			}
		}

		/// <summary>
		/// Vráti atribút IId.
		/// </summary>
		/// <value>atribút IId.</value>
		public int col_IId
		{
			get
			{
				return _col_IId;
			}
			internal set
			{
				_col_IId = value;
			}
		}

		/// <summary>
		/// Vráti atribút Meno.
		/// </summary>
		/// <value>atribút Meno; alebo <c>null</c>.</value>
		public string col_Meno
		{
			get
			{
				return _col_Meno;
			}
			internal set
			{
				_col_Meno = value;
			}
		}

		/// <summary>
		/// Vráti atribút Priez.
		/// </summary>
		/// <value>atribút Priez; alebo <c>null</c>.</value>
		public string col_Priez
		{
			get
			{
				return _col_Priez;
			}
			internal set
			{
				_col_Priez = value;
			}
		}

		/// <summary>
		/// Vráti atribút NP.
		/// </summary>
		/// <value>atribút NP; alebo <c>null</c>.</value>
		public string col_NP
		{
			get
			{
				return _col_NP;
			}
			internal set
			{
				_col_NP = value;
			}
		}

		/// <summary>
		/// Vráti atribút NM.
		/// </summary>
		/// <value>atribút NM; alebo <c>null</c>.</value>
		public string col_NM
		{
			get
			{
				return _col_NM;
			}
			internal set
			{
				_col_NM = value;
			}
		}

		/// <summary>
		/// Vráti atribút ICmFormat.
		/// </summary>
		/// <value>atribút ICmFormat; alebo <c>null</c>.</value>
		public string col_ICmFormat
		{
			get
			{
				return _col_ICmFormat;
			}
			internal set
			{
				_col_ICmFormat = value;
			}
		}

		/// <summary>
		/// Vráti atribút NCm.
		/// </summary>
		/// <value>atribút NCm; alebo <c>null</c>.</value>
		public string col_NCm
		{
			get
			{
				return _col_NCm;
			}
			internal set
			{
				_col_NCm = value;
			}
		}

		/// <summary>
		/// Vráti atribút IUFormat.
		/// </summary>
		/// <value>atribút IUFormat; alebo <c>null</c>.</value>
		public string col_IUFormat
		{
			get
			{
				return _col_IUFormat;
			}
			internal set
			{
				_col_IUFormat = value;
			}
		}

		/// <summary>
		/// Vráti atribút NU.
		/// </summary>
		/// <value>atribút NU; alebo <c>null</c>.</value>
		public string col_NU
		{
			get
			{
				return _col_NU;
			}
			internal set
			{
				_col_NU = value;
			}
		}

		/// <summary>
		/// Vráti atribút Cs.
		/// </summary>
		/// <value>atribút Cs; alebo <c>null</c>.</value>
		public string col_Cs
		{
			get
			{
				return _col_Cs;
			}
			internal set
			{
				_col_Cs = value;
			}
		}

		/// <summary>
		/// Vráti atribút Co.
		/// </summary>
		/// <value>atribút Co; alebo <c>null</c>.</value>
		public string col_Co
		{
			get
			{
				return _col_Co;
			}
			internal set
			{
				_col_Co = value;
			}
		}

		/// <summary>
		/// Vráti atribút Psc.
		/// </summary>
		/// <value>atribút Psc; alebo <c>null</c>.</value>
		public string col_Psc
		{
			get
			{
				return _col_Psc;
			}
			internal set
			{
				_col_Psc = value;
			}
		}

		/// <summary>
		/// Vráti atribút NVztDr.
		/// </summary>
		/// <value>atribút NVztDr; alebo <c>null</c>.</value>
		public string col_NVztDr
		{
			get
			{
				return _col_NVztDr;
			}
			internal set
			{
				_col_NVztDr = value;
			}
		}

		/// <summary>
		/// Vráti atribút DanCelkPr.
		/// </summary>
		/// <value>atribút DanCelkPr; alebo <c>null</c>.</value>
		public decimal? col_DanCelkPr
		{
			get
			{
				return _col_DanCelkPr;
			}
			internal set
			{
				_col_DanCelkPr = value;
			}
		}

		/// <summary>
		/// Vráti atribút Vym.
		/// </summary>
		/// <value>atribút Vym; alebo <c>null</c>.</value>
		public decimal? col_Vym
		{
			get
			{
				return _col_Vym;
			}
			internal set
			{
				_col_Vym = value;
			}
		}

		/// <summary>
		/// Vráti atribút LZalPrav.
		/// </summary>
		/// <value>atribút LZalPrav.</value>
		public bool col_LZalPrav
		{
			get
			{
				return _col_LZalPrav;
			}
			internal set
			{
				_col_LZalPrav = value;
			}
		}

		/// <summary>
		/// Vráti atribút ParcIdentif.
		/// </summary>
		/// <value>atribút ParcIdentif; alebo <c>null</c>.</value>
		public string col_ParcIdentif
		{
			get
			{
				return _col_ParcIdentif;
			}
			internal set
			{
				_col_ParcIdentif = value;
			}
		}

		/// <summary>
		/// Vráti atribút DModify.
		/// </summary>
		/// <value>atribút DModify; alebo <c>null</c>.</value>
		public DateTime? col_DModify
		{
			get
			{
				return _col_DModify;
			}
			internal set
			{
				_col_DModify = value;
			}
		}

		/// <summary>
		/// Vráti atribút ChangeType.
		/// </summary>
		/// <value>atribút ChangeType; alebo <c>null</c>.</value>
		public int? col_ChangeType
		{
			get
			{
				return _col_ChangeType;
			}
			internal set
			{
				_col_ChangeType = value;
			}
		}

		#endregion

		#region Public Methods

		/// <summary>
		/// Načíta atribúty inštancie z dátového reader-a.
		/// </summary>
		/// <param name="oResult">Dátový reader. Názvy stĺpcov v reader-i musia zodpovedať názvom stĺpcov tabuľky.</param>
		/// <returns>Vždy <c>true</c>.</returns>
		public override void fillAttributes(IDataReader oResult)
		{
			_setAttrib(out _col_IId, oResult["IId"]);
			_setAttrib(out _col_Meno, oResult["Meno"]);
			_setAttrib(out _col_Priez, oResult["Priez"]);
			_setAttrib(out _col_NP, oResult["NP"]);
			_setAttrib(out _col_NM, oResult["NM"]);
			_setAttrib(out _col_ICmFormat, oResult["ICmFormat"]);
			_setAttrib(out _col_NCm, oResult["NCm"]);
			_setAttrib(out _col_IUFormat, oResult["IUFormat"]);
			_setAttrib(out _col_NU, oResult["NU"]);
			_setAttrib(out _col_Cs, oResult["Cs"]);
			_setAttrib(out _col_Co, oResult["Co"]);
			_setAttrib(out _col_Psc, oResult["Psc"]);
			_setAttrib(out _col_NVztDr, oResult["NVztDr"]);
			_setAttrib(out _col_DanCelkPr, oResult["DanCelkPr"]);
			_setAttrib(out _col_Vym, oResult["Vym"]);
			_setAttrib(out _col_LZalPrav, oResult["LZalPrav"]);
			_setAttrib(out _col_ParcIdentif, oResult["ParcIdentif"]);
			_setAttrib(out _col_DModify, oResult["DModify"]);
			_setAttrib(out _col_ChangeType, oResult["ChangeType"]);
		}

		/// <summary>
		/// Inicializuje inštanciu.
		/// </summary>
		public override bool Init()
		{
			base._classID = 293075000;
			sTabMain = "MET_DN_POZ";
			sTabs = "MET_DN_POZ";
			sColPK = "IId";
			sCols = "IId,Meno,Priez,NP,NM,ICmFormat,NCm,IUFormat,NU,Cs,Co,Psc,NVztDr,DanCelkPr,Vym,LZalPrav,ParcIdentif,DModify,ChangeType";
			return true;
		}

		#endregion

		#region Protected Methods

		#endregion

		private int _col_IId;
		private string _col_Meno;
		private string _col_Priez;
		private string _col_NP;
		private string _col_NM;
		private string _col_ICmFormat;
		private string _col_NCm;
		private string _col_IUFormat;
		private string _col_NU;
		private string _col_Cs;
		private string _col_Co;
		private string _col_Psc;
		private string _col_NVztDr;
		private decimal? _col_DanCelkPr;
		private decimal? _col_Vym;
		private bool _col_LZalPrav;
		private string _col_ParcIdentif;
		private DateTime? _col_DModify;
		private int? _col_ChangeType;
	}
}