// Generated by NATeC ClassGenerator v. 4.2.2014.502
// Source model: D:\svnroot\proj\Portal_ISS\extra\2016.4.0\Analyzy a davky\HD 44497\NE_HD44497_upravene.pdm
// Please do not edit this file - for custom additions to this class use a separate *$cust.cs file instead.
// Class Options: IMMUTABLE NOARCHIVE

using System;
using System.Data;
using Cora.Data.DBProvider;
using Cora.Natec.Base;

namespace Cora.CoraApp.ISS.EXT.MAT
{
	/// <summary>
	/// MET_C_PA_MM (business trieda).
	/// </summary>
	[Serializable]
	public partial class CdoMET_C_PA_MM : clsDataObjR
	{
		#region Properties

		/// <summary>
		/// Vráti primárny kľúč.
		/// </summary>
		/// <value>Primárny kľúč.</value>
		public override long iPK
		{
			get
			{
				return _col_IId;
			}
			set
			{
				_col_IId = (int)value;
			}
		}

		/// <summary>
		/// Vráti atribút IId.
		/// </summary>
		/// <value>atribút IId.</value>
		public int col_IId
		{
			get
			{
				return _col_IId;
			}
			internal set
			{
				_col_IId = value;
			}
		}

		/// <summary>
		/// Vráti atribút VymKn.
		/// </summary>
		/// <value>atribút VymKn; alebo <c>null</c>.</value>
		public decimal? col_VymKn
		{
			get
			{
				return _col_VymKn;
			}
			internal set
			{
				_col_VymKn = value;
			}
		}

		/// <summary>
		/// Vráti atribút ParcIdentif.
		/// </summary>
		/// <value>atribút ParcIdentif; alebo <c>null</c>.</value>
		public string col_ParcIdentif
		{
			get
			{
				return _col_ParcIdentif;
			}
			internal set
			{
				_col_ParcIdentif = value;
			}
		}

		/// <summary>
		/// Vráti atribút NCNmDr.
		/// </summary>
		/// <value>atribút NCNmDr; alebo <c>null</c>.</value>
		public string col_NCNmDr
		{
			get
			{
				return _col_NCNmDr;
			}
			internal set
			{
				_col_NCNmDr = value;
			}
		}

		/// <summary>
		/// Vráti atribút DModify.
		/// </summary>
		/// <value>atribút DModify; alebo <c>null</c>.</value>
		public DateTime? col_DModify
		{
			get
			{
				return _col_DModify;
			}
			internal set
			{
				_col_DModify = value;
			}
		}

		/// <summary>
		/// Vráti atribút ChangeType.
		/// </summary>
		/// <value>atribút ChangeType; alebo <c>null</c>.</value>
		public int? col_ChangeType
		{
			get
			{
				return _col_ChangeType;
			}
			internal set
			{
				_col_ChangeType = value;
			}
		}

		#endregion

		#region Public Methods

		/// <summary>
		/// Načíta atribúty inštancie z dátového reader-a.
		/// </summary>
		/// <param name="oResult">Dátový reader. Názvy stĺpcov v reader-i musia zodpovedať názvom stĺpcov tabuľky.</param>
		/// <returns>Vždy <c>true</c>.</returns>
		public override void fillAttributes(IDataReader oResult)
		{
			_setAttrib(out _col_IId, oResult["IId"]);
			_setAttrib(out _col_VymKn, oResult["VymKn"]);
			_setAttrib(out _col_ParcIdentif, oResult["ParcIdentif"]);
			_setAttrib(out _col_NCNmDr, oResult["NCNmDr"]);
			_setAttrib(out _col_DModify, oResult["DModify"]);
			_setAttrib(out _col_ChangeType, oResult["ChangeType"]);
		}

		/// <summary>
		/// Inicializuje inštanciu.
		/// </summary>
		public override bool Init()
		{
			base._classID = 293072000;
			sTabMain = "MET_C_PA_MM";
			sTabs = "MET_C_PA_MM";
			sColPK = "IId";
			sCols = "IId,VymKn,ParcIdentif,NCNmDr,DModify,ChangeType";
			return true;
		}

		#endregion

		#region Protected Methods

		#endregion

		private int _col_IId;
		private decimal? _col_VymKn;
		private string _col_ParcIdentif;
		private string _col_NCNmDr;
		private DateTime? _col_DModify;
		private int? _col_ChangeType;
	}
}