// Generated by NATeC ClassGenerator v. 4.2.2014.502
// Source model: D:\svnroot\proj\Portal_ISS\extra\2016.4.0\Analyzy a davky\HD 44497\NE_HD44497_upravene.pdm
// Please do not edit this file - for custom additions to this class use a separate *$cust.cs file instead.
// Class Options: IMMUTABLE NOARCHIVE

using System;
using System.Data;
using Cora.Data.DBProvider;
using Cora.Natec.Base;

namespace Cora.CoraApp.ISS.EXT.MAT
{
	/// <summary>
	/// MET_C_CM (business trieda).
	/// </summary>
	[Serializable]
	public partial class CdoMET_C_CM : clsDataObjR
	{
		#region Properties

		/// <summary>
		/// Vráti primárny kľúč.
		/// </summary>
		/// <value>Primárny kľúč.</value>
		public override long iPK
		{
			get
			{
				return _col_ICm;
			}
			set
			{
				_col_ICm = (int)value;
			}
		}

		/// <summary>
		/// Vráti atribút ICm.
		/// </summary>
		/// <value>atribút ICm.</value>
		public int col_ICm
		{
			get
			{
				return _col_ICm;
			}
			internal set
			{
				_col_ICm = value;
			}
		}

		/// <summary>
		/// Vráti atribút ICmFormat.
		/// </summary>
		/// <value>atribút ICmFormat; alebo <c>null</c>.</value>
		public string col_ICmFormat
		{
			get
			{
				return _col_ICmFormat;
			}
			internal set
			{
				_col_ICmFormat = value;
			}
		}

		/// <summary>
		/// Vráti atribút NCm.
		/// </summary>
		/// <value>atribút NCm; alebo <c>null</c>.</value>
		public string col_NCm
		{
			get
			{
				return _col_NCm;
			}
			internal set
			{
				_col_NCm = value;
			}
		}

		/// <summary>
		/// Vráti atribút DModify.
		/// </summary>
		/// <value>atribút DModify; alebo <c>null</c>.</value>
		public DateTime? col_DModify
		{
			get
			{
				return _col_DModify;
			}
			internal set
			{
				_col_DModify = value;
			}
		}

		/// <summary>
		/// Vráti atribút ChangeType.
		/// </summary>
		/// <value>atribút ChangeType; alebo <c>null</c>.</value>
		public int? col_ChangeType
		{
			get
			{
				return _col_ChangeType;
			}
			internal set
			{
				_col_ChangeType = value;
			}
		}

		#endregion

		#region Public Methods

		/// <summary>
		/// Načíta atribúty inštancie z dátového reader-a.
		/// </summary>
		/// <param name="oResult">Dátový reader. Názvy stĺpcov v reader-i musia zodpovedať názvom stĺpcov tabuľky.</param>
		/// <returns>Vždy <c>true</c>.</returns>
		public override void fillAttributes(IDataReader oResult)
		{
			_setAttrib(out _col_ICm, oResult["ICm"]);
			_setAttrib(out _col_ICmFormat, oResult["ICmFormat"]);
			_setAttrib(out _col_NCm, oResult["NCm"]);
			_setAttrib(out _col_DModify, oResult["DModify"]);
			_setAttrib(out _col_ChangeType, oResult["ChangeType"]);
		}

		/// <summary>
		/// Inicializuje inštanciu.
		/// </summary>
		public override bool Init()
		{
			base._classID = 293071000;
			sTabMain = "MET_C_CM";
			sTabs = "MET_C_CM";
			sColPK = "ICm";
			sCols = "ICm,ICmFormat,NCm,DModify,ChangeType";
			return true;
		}

		#endregion

		#region Protected Methods

		#endregion

		private int _col_ICm;
		private string _col_ICmFormat;
		private string _col_NCm;
		private DateTime? _col_DModify;
		private int? _col_ChangeType;
	}
}