// Generated by NATeC ClassGenerator v. 4.2.2014.502
// Source model: D:\svnroot\proj\Portal_ISS\extra\2016.4.0\Analyzy a davky\HD 44497\NE_HD44497_upravene.pdm
// Please do not edit this file - for custom additions to this class use a separate *$cust.cs file instead.
// Class Options: IMMUTABLE NOARCHIVE

using System;
using System.Runtime.Serialization;
using Cora.Natec.Base;

namespace Cora.CoraApp.ISS.EXT.MAT
{
	/// <summary>
	/// Transfer trieda pre <see cref="CdoMET_C_U"/>.
	/// </summary>
	[Serializable]
	[DataContract(Namespace="http://www.corageo.sk/")]
	public partial class CtoMET_C_U
	{
		public long iPK
		{
			get { return IU; }
		}

		[DataMember]
		public int IU { get; set; }
		[DataMember]
		public string IUFormat { get; set; }
		[DataMember]
		public string NU { get; set; }
		[DataMember]
		public DateTime? DModify { get; set; }
		[DataMember]
		public int? ChangeType { get; set; }
	}

	/// <summary>
	/// Trieda pre konverziu medzi <see cref="CdoMET_C_U"/> a <see cref="CtoMET_C_U"/>.
	/// </summary>
	public static class CtoMET_C_UExtensions
	{
		/// <summary>
		/// Konvertuje business objekt na transfer objekt.
		/// </summary>
		/// <param name="cdo">Business objekt.</param>
		/// <value>Transfer objekt, alebo <c>null</c> ak je business objekt <c>null</c>.</value>
		public static CtoMET_C_U ToDto(this CdoMET_C_U cdo)
		{
			if ( null == cdo )
				return null;

			return new CtoMET_C_U()
			{
				IU = cdo.col_IU,
				IUFormat = cdo.col_IUFormat,
				NU = cdo.col_NU,
				DModify = cdo.col_DModify,
				ChangeType = cdo.col_ChangeType,
			};
		}

		/// <summary>
		/// Konvertuje transfer objekt na business objekt.
		/// </summary>
		/// <param name="dto">Transfer objekt.</param>
		/// <value>Business objekt, alebo <c>null</c> ak je transfer objekt <c>null</c>.</value>
		public static CdoMET_C_U ToCdo(this CtoMET_C_U dto)
		{
			if ( null == dto )
				return null;

			CdoMET_C_U ret = FactoryFactory.GetSFactory<CdoMET_C_U>().GetNew();
			ret.LoadDto(dto);
			return ret;
		}

		/// <summary>
		/// Nahrá dáta z transfer objektu do business objektu.
		/// </summary>
		/// <param name="cdo">Business objekt.</param>
		/// <param name="dto">Transfer objekt.</param>
		public static void LoadDto(this CdoMET_C_U cdo, CtoMET_C_U dto)
		{
			cdo.col_IU = dto.IU;
			cdo.col_IUFormat = dto.IUFormat;
			cdo.col_NU = dto.NU;
			cdo.col_DModify = dto.DModify;
			cdo.col_ChangeType = dto.ChangeType;
		}
	}
}