// Generated by NATeC ClassGenerator v. 4.2.2014.502
// Source model: D:\svnroot\proj\Portal_ISS\extra\2016.4.0\Analyzy a davky\HD 44497\NE_HD44497_upravene.pdm
// Please do not edit this file - for custom additions to this class use a separate *$cust.cs file instead.
// Class Options: IMMUTABLE NOARCHIVE

using System;
using System.Runtime.Serialization;
using Cora.Natec.Base;

namespace Cora.CoraApp.ISS.EXT.MAT
{
	/// <summary>
	/// Transfer trieda pre <see cref="CdoMET_DN_POZ"/>.
	/// </summary>
	[Serializable]
	[DataContract(Namespace="http://www.corageo.sk/")]
	public partial class CtoMET_DN_POZ
	{
#pragma warning disable 1591
		public long iPK
		{
			get { return IId; }
		}

		[DataMember]
		public int IId { get; set; }
		[DataMember]
		public string Meno { get; set; }
		[DataMember]
		public string Priez { get; set; }
		[DataMember]
		public string NP { get; set; }
		[DataMember]
		public string NM { get; set; }
		[DataMember]
		public string ICmFormat { get; set; }
		[DataMember]
		public string NCm { get; set; }
		[DataMember]
		public string IUFormat { get; set; }
		[DataMember]
		public string NU { get; set; }
		[DataMember]
		public string Cs { get; set; }
		[DataMember]
		public string Co { get; set; }
		[DataMember]
		public string Psc { get; set; }
		[DataMember]
		public string NVztDr { get; set; }
		[DataMember]
		public decimal? DanCelkPr { get; set; }
		[DataMember]
		public decimal? Vym { get; set; }
		[DataMember]
		public bool LZalPrav { get; set; }
		[DataMember]
		public string ParcIdentif { get; set; }
		[DataMember]
		public DateTime? DModify { get; set; }
		[DataMember]
		public int? ChangeType { get; set; }
#pragma warning restore 1591
	}

	/// <summary>
	/// Trieda pre konverziu medzi <see cref="CdoMET_DN_POZ"/> a <see cref="CtoMET_DN_POZ"/>.
	/// </summary>
	public static class CtoMET_DN_POZExtensions
	{
		/// <summary>
		/// Konvertuje business objekt na transfer objekt.
		/// </summary>
		/// <param name="cdo">Business objekt.</param>
		/// <value>Transfer objekt, alebo <c>null</c> ak je business objekt <c>null</c>.</value>
		public static CtoMET_DN_POZ ToDto(this CdoMET_DN_POZ cdo)
		{
			if ( null == cdo )
				return null;

			return new CtoMET_DN_POZ()
			{
				IId = cdo.col_IId,
				Meno = cdo.col_Meno,
				Priez = cdo.col_Priez,
				NP = cdo.col_NP,
				NM = cdo.col_NM,
				ICmFormat = cdo.col_ICmFormat,
				NCm = cdo.col_NCm,
				IUFormat = cdo.col_IUFormat,
				NU = cdo.col_NU,
				Cs = cdo.col_Cs,
				Co = cdo.col_Co,
				Psc = cdo.col_Psc,
				NVztDr = cdo.col_NVztDr,
				DanCelkPr = cdo.col_DanCelkPr,
				Vym = cdo.col_Vym,
				LZalPrav = cdo.col_LZalPrav,
				ParcIdentif = cdo.col_ParcIdentif,
				DModify = cdo.col_DModify,
				ChangeType = cdo.col_ChangeType,
			};
		}

		/// <summary>
		/// Konvertuje transfer objekt na business objekt.
		/// </summary>
		/// <param name="dto">Transfer objekt.</param>
		/// <value>Business objekt, alebo <c>null</c> ak je transfer objekt <c>null</c>.</value>
		public static CdoMET_DN_POZ ToCdo(this CtoMET_DN_POZ dto)
		{
			if ( null == dto )
				return null;

			CdoMET_DN_POZ ret = FactoryFactory.GetSFactory<CdoMET_DN_POZ>().GetNew();
			ret.LoadDto(dto);
			return ret;
		}

		/// <summary>
		/// Nahrá dáta z transfer objektu do business objektu.
		/// </summary>
		/// <param name="cdo">Business objekt.</param>
		/// <param name="dto">Transfer objekt.</param>
		public static void LoadDto(this CdoMET_DN_POZ cdo, CtoMET_DN_POZ dto)
		{
			cdo.col_IId = dto.IId;
			cdo.col_Meno = dto.Meno;
			cdo.col_Priez = dto.Priez;
			cdo.col_NP = dto.NP;
			cdo.col_NM = dto.NM;
			cdo.col_ICmFormat = dto.ICmFormat;
			cdo.col_NCm = dto.NCm;
			cdo.col_IUFormat = dto.IUFormat;
			cdo.col_NU = dto.NU;
			cdo.col_Cs = dto.Cs;
			cdo.col_Co = dto.Co;
			cdo.col_Psc = dto.Psc;
			cdo.col_NVztDr = dto.NVztDr;
			cdo.col_DanCelkPr = dto.DanCelkPr;
			cdo.col_Vym = dto.Vym;
			cdo.col_LZalPrav = dto.LZalPrav;
			cdo.col_ParcIdentif = dto.ParcIdentif;
			cdo.col_DModify = dto.DModify;
			cdo.col_ChangeType = dto.ChangeType;
		}
	}
}