// Generated by NATeC ClassGenerator v. 4.2.2014.502
// Source model: D:\svnroot\proj\Portal_ISS\extra\2016.4.0\Analyzy a davky\HD 44497\NE_HD44497_upravene.pdm
// Please do not edit this file - for custom additions to this class use a separate *$cust.cs file instead.
// Class Options: IMMUTABLE NOARCHIVE

using System;
using System.Runtime.Serialization;
using Cora.Natec.Base;

namespace Cora.CoraApp.ISS.EXT.MAT
{
	/// <summary>
	/// Transfer trieda pre <see cref="CdoMET_PO_PES"/>.
	/// </summary>
	[Serializable]
	[DataContract(Namespace="http://www.corageo.sk/")]
	public partial class CtoMET_PO_PES
	{
#pragma warning disable 1591
		public long iPK
		{
			get { return IPes; }
		}

		[DataMember]
		public int IPes { get; set; }
		[DataMember]
		public string Meno { get; set; }
		[DataMember]
		public string Pf { get; set; }
		[DataMember]
		public string NM { get; set; }
		[DataMember]
		public string ICmFormat { get; set; }
		[DataMember]
		public string NCm { get; set; }
		[DataMember]
		public string IUFormat { get; set; }
		[DataMember]
		public string NU { get; set; }
		[DataMember]
		public string Cs { get; set; }
		[DataMember]
		public string Co { get; set; }
		[DataMember]
		public string Psc { get; set; }
		[DataMember]
		public string NCPlem { get; set; }
		[DataMember]
		public bool LNebezpecny { get; set; }
		[DataMember]
		public string CZnamka { get; set; }
		[DataMember]
		public string AdrIdentif { get; set; }
		[DataMember]
		public DateTime? DModify { get; set; }
		[DataMember]
		public int? ChangeType { get; set; }
#pragma warning restore 1591
	}

	/// <summary>
	/// Trieda pre konverziu medzi <see cref="CdoMET_PO_PES"/> a <see cref="CtoMET_PO_PES"/>.
	/// </summary>
	public static class CtoMET_PO_PESExtensions
	{
		/// <summary>
		/// Konvertuje business objekt na transfer objekt.
		/// </summary>
		/// <param name="cdo">Business objekt.</param>
		/// <value>Transfer objekt, alebo <c>null</c> ak je business objekt <c>null</c>.</value>
		public static CtoMET_PO_PES ToDto(this CdoMET_PO_PES cdo)
		{
			if ( null == cdo )
				return null;

			return new CtoMET_PO_PES()
			{
				IPes = cdo.col_IPes,
				Meno = cdo.col_Meno,
				Pf = cdo.col_Pf,
				NM = cdo.col_NM,
				ICmFormat = cdo.col_ICmFormat,
				NCm = cdo.col_NCm,
				IUFormat = cdo.col_IUFormat,
				NU = cdo.col_NU,
				Cs = cdo.col_Cs,
				Co = cdo.col_Co,
				Psc = cdo.col_Psc,
				NCPlem = cdo.col_NCPlem,
				LNebezpecny = cdo.col_LNebezpecny,
				CZnamka = cdo.col_CZnamka,
				AdrIdentif = cdo.col_AdrIdentif,
				DModify = cdo.col_DModify,
				ChangeType = cdo.col_ChangeType,
			};
		}

		/// <summary>
		/// Konvertuje transfer objekt na business objekt.
		/// </summary>
		/// <param name="dto">Transfer objekt.</param>
		/// <value>Business objekt, alebo <c>null</c> ak je transfer objekt <c>null</c>.</value>
		public static CdoMET_PO_PES ToCdo(this CtoMET_PO_PES dto)
		{
			if ( null == dto )
				return null;

			CdoMET_PO_PES ret = FactoryFactory.GetSFactory<CdoMET_PO_PES>().GetNew();
			ret.LoadDto(dto);
			return ret;
		}

		/// <summary>
		/// Nahrá dáta z transfer objektu do business objektu.
		/// </summary>
		/// <param name="cdo">Business objekt.</param>
		/// <param name="dto">Transfer objekt.</param>
		public static void LoadDto(this CdoMET_PO_PES cdo, CtoMET_PO_PES dto)
		{
			cdo.col_IPes = dto.IPes;
			cdo.col_Meno = dto.Meno;
			cdo.col_Pf = dto.Pf;
			cdo.col_NM = dto.NM;
			cdo.col_ICmFormat = dto.ICmFormat;
			cdo.col_NCm = dto.NCm;
			cdo.col_IUFormat = dto.IUFormat;
			cdo.col_NU = dto.NU;
			cdo.col_Cs = dto.Cs;
			cdo.col_Co = dto.Co;
			cdo.col_Psc = dto.Psc;
			cdo.col_NCPlem = dto.NCPlem;
			cdo.col_LNebezpecny = dto.LNebezpecny;
			cdo.col_CZnamka = dto.CZnamka;
			cdo.col_AdrIdentif = dto.AdrIdentif;
			cdo.col_DModify = dto.DModify;
			cdo.col_ChangeType = dto.ChangeType;
		}
	}
}