//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cora.CommIss.Iss.ZelenaPostaRequireClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.zelenaposta.sk/api/mailing", ConfigurationName="ZelenaPostaRequireClient.Mailing")]
    public interface Mailing {
        
        // CODEGEN: Generating message contract since the operation list is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cora.CommIss.Iss.ZelenaPostaRequireClient.listResponse1 list(Cora.CommIss.Iss.ZelenaPostaRequireClient.listRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaRequireClient.listResponse1> listAsync(Cora.CommIss.Iss.ZelenaPostaRequireClient.listRequest1 request);
        
        // CODEGEN: Generating message contract since the operation prepare is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cora.CommIss.Iss.ZelenaPostaRequireClient.prepareResponse1 prepare(Cora.CommIss.Iss.ZelenaPostaRequireClient.prepareRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaRequireClient.prepareResponse1> prepareAsync(Cora.CommIss.Iss.ZelenaPostaRequireClient.prepareRequest1 request);
        
        // CODEGEN: Generating message contract since the operation send is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cora.CommIss.Iss.ZelenaPostaRequireClient.sendResponse1 send(Cora.CommIss.Iss.ZelenaPostaRequireClient.sendRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaRequireClient.sendResponse1> sendAsync(Cora.CommIss.Iss.ZelenaPostaRequireClient.sendRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getProducts is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cora.CommIss.Iss.ZelenaPostaRequireClient.getProductsResponse1 getProducts(Cora.CommIss.Iss.ZelenaPostaRequireClient.getProductsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaRequireClient.getProductsResponse1> getProductsAsync(Cora.CommIss.Iss.ZelenaPostaRequireClient.getProductsRequest1 request);
        
        // CODEGEN: Generating message contract since the operation sendElectronic is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cora.CommIss.Iss.ZelenaPostaRequireClient.sendElectronicResponse1 sendElectronic(Cora.CommIss.Iss.ZelenaPostaRequireClient.sendElectronicRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaRequireClient.sendElectronicResponse1> sendElectronicAsync(Cora.CommIss.Iss.ZelenaPostaRequireClient.sendElectronicRequest1 request);
        
        // CODEGEN: Generating message contract since the operation delete is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cora.CommIss.Iss.ZelenaPostaRequireClient.deleteResponse1 delete(Cora.CommIss.Iss.ZelenaPostaRequireClient.deleteRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaRequireClient.deleteResponse1> deleteAsync(Cora.CommIss.Iss.ZelenaPostaRequireClient.deleteRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.zelenaposta.sk/api/mailing")]
    public partial class listRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime statusChangedSinceField;
        
        private bool statusChangedSinceFieldSpecified;
        
        private System.DateTime statusChangedUntilField;
        
        private bool statusChangedUntilFieldSpecified;
        
        private string[] slotIdsField;
        
        private int[] idsField;
        
        private string[] customIdsField;
        
        private int limitField;
        
        private bool limitFieldSpecified;
        
        private int offsetField;
        
        private bool offsetFieldSpecified;
        
        /// <remarks/>
        public System.DateTime statusChangedSince {
            get {
                return this.statusChangedSinceField;
            }
            set {
                this.statusChangedSinceField = value;
                this.RaisePropertyChanged("statusChangedSince");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusChangedSinceSpecified {
            get {
                return this.statusChangedSinceFieldSpecified;
            }
            set {
                this.statusChangedSinceFieldSpecified = value;
                this.RaisePropertyChanged("statusChangedSinceSpecified");
            }
        }
        
        /// <remarks/>
        public System.DateTime statusChangedUntil {
            get {
                return this.statusChangedUntilField;
            }
            set {
                this.statusChangedUntilField = value;
                this.RaisePropertyChanged("statusChangedUntil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusChangedUntilSpecified {
            get {
                return this.statusChangedUntilFieldSpecified;
            }
            set {
                this.statusChangedUntilFieldSpecified = value;
                this.RaisePropertyChanged("statusChangedUntilSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("slotId", IsNullable=false)]
        public string[] slotIds {
            get {
                return this.slotIdsField;
            }
            set {
                this.slotIdsField = value;
                this.RaisePropertyChanged("slotIds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("id", IsNullable=false)]
        public int[] ids {
            get {
                return this.idsField;
            }
            set {
                this.idsField = value;
                this.RaisePropertyChanged("ids");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("customId", IsNullable=false)]
        public string[] customIds {
            get {
                return this.customIdsField;
            }
            set {
                this.customIdsField = value;
                this.RaisePropertyChanged("customIds");
            }
        }
        
        /// <remarks/>
        public int limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
                this.RaisePropertyChanged("limit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool limitSpecified {
            get {
                return this.limitFieldSpecified;
            }
            set {
                this.limitFieldSpecified = value;
                this.RaisePropertyChanged("limitSpecified");
            }
        }
        
        /// <remarks/>
        public int offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
                this.RaisePropertyChanged("offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool offsetSpecified {
            get {
                return this.offsetFieldSpecified;
            }
            set {
                this.offsetFieldSpecified = value;
                this.RaisePropertyChanged("offsetSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.zelenaposta.sk/api/mailing")]
    public partial class addressType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string streetField;
        
        private string cityField;
        
        private string zipField;
        
        private string countryField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("street");
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        public string zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("zip");
            }
        }
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.zelenaposta.sk/api/mailing")]
    public partial class listResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private listResponseMailing[] mailingsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("mailing", IsNullable=false)]
        public listResponseMailing[] mailings {
            get {
                return this.mailingsField;
            }
            set {
                this.mailingsField = value;
                this.RaisePropertyChanged("mailings");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.zelenaposta.sk/api/mailing")]
    public partial class listResponseMailing : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string statusField;
        
        private System.DateTime statusChangedOnField;
        
        private bool statusChangedOnFieldSpecified;
        
        private int bundleIdField;
        
        private bool bundleIdFieldSpecified;
        
        private string slotIdField;
        
        private string uidField;
        
        private string pinField;
        
        private string uiz1Field;
        
        private string uiz2Field;
        
        private string productField;
        
        private System.DateTime filingDateField;
        
        private bool filingDateFieldSpecified;
        
        private addressType recipientField;
        
        private addressType senderField;
        
        private string registeredPostIdField;
        
        private string customIdField;
        
        private decimal postageWithVatField;
        
        private decimal productWithVatField;
        
        private int pageCountField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        public System.DateTime statusChangedOn {
            get {
                return this.statusChangedOnField;
            }
            set {
                this.statusChangedOnField = value;
                this.RaisePropertyChanged("statusChangedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusChangedOnSpecified {
            get {
                return this.statusChangedOnFieldSpecified;
            }
            set {
                this.statusChangedOnFieldSpecified = value;
                this.RaisePropertyChanged("statusChangedOnSpecified");
            }
        }
        
        /// <remarks/>
        public int bundleId {
            get {
                return this.bundleIdField;
            }
            set {
                this.bundleIdField = value;
                this.RaisePropertyChanged("bundleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bundleIdSpecified {
            get {
                return this.bundleIdFieldSpecified;
            }
            set {
                this.bundleIdFieldSpecified = value;
                this.RaisePropertyChanged("bundleIdSpecified");
            }
        }
        
        /// <remarks/>
        public string slotId {
            get {
                return this.slotIdField;
            }
            set {
                this.slotIdField = value;
                this.RaisePropertyChanged("slotId");
            }
        }
        
        /// <remarks/>
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
                this.RaisePropertyChanged("uid");
            }
        }
        
        /// <remarks/>
        public string pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
                this.RaisePropertyChanged("pin");
            }
        }
        
        /// <remarks/>
        public string uiz1 {
            get {
                return this.uiz1Field;
            }
            set {
                this.uiz1Field = value;
                this.RaisePropertyChanged("uiz1");
            }
        }
        
        /// <remarks/>
        public string uiz2 {
            get {
                return this.uiz2Field;
            }
            set {
                this.uiz2Field = value;
                this.RaisePropertyChanged("uiz2");
            }
        }
        
        /// <remarks/>
        public string product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
                this.RaisePropertyChanged("product");
            }
        }
        
        /// <remarks/>
        public System.DateTime filingDate {
            get {
                return this.filingDateField;
            }
            set {
                this.filingDateField = value;
                this.RaisePropertyChanged("filingDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool filingDateSpecified {
            get {
                return this.filingDateFieldSpecified;
            }
            set {
                this.filingDateFieldSpecified = value;
                this.RaisePropertyChanged("filingDateSpecified");
            }
        }
        
        /// <remarks/>
        public addressType recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
                this.RaisePropertyChanged("recipient");
            }
        }
        
        /// <remarks/>
        public addressType sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("sender");
            }
        }
        
        /// <remarks/>
        public string registeredPostId {
            get {
                return this.registeredPostIdField;
            }
            set {
                this.registeredPostIdField = value;
                this.RaisePropertyChanged("registeredPostId");
            }
        }
        
        /// <remarks/>
        public string customId {
            get {
                return this.customIdField;
            }
            set {
                this.customIdField = value;
                this.RaisePropertyChanged("customId");
            }
        }
        
        /// <remarks/>
        public decimal postageWithVat {
            get {
                return this.postageWithVatField;
            }
            set {
                this.postageWithVatField = value;
                this.RaisePropertyChanged("postageWithVat");
            }
        }
        
        /// <remarks/>
        public decimal productWithVat {
            get {
                return this.productWithVatField;
            }
            set {
                this.productWithVatField = value;
                this.RaisePropertyChanged("productWithVat");
            }
        }
        
        /// <remarks/>
        public int pageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
                this.RaisePropertyChanged("pageCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.zelenaposta.sk/api/mailing", Order=0)]
        public Cora.CommIss.Iss.ZelenaPostaRequireClient.listRequest listRequest;
        
        public listRequest1() {
        }
        
        public listRequest1(Cora.CommIss.Iss.ZelenaPostaRequireClient.listRequest listRequest) {
            this.listRequest = listRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.zelenaposta.sk/api/mailing", Order=0)]
        public Cora.CommIss.Iss.ZelenaPostaRequireClient.listResponse listResponse;
        
        public listResponse1() {
        }
        
        public listResponse1(Cora.CommIss.Iss.ZelenaPostaRequireClient.listResponse listResponse) {
            this.listResponse = listResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.zelenaposta.sk/api/mailing")]
    public partial class prepareRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool printedField;
        
        private bool printedFieldSpecified;
        
        private prepareRequestMailing[] mailingsField;
        
        /// <remarks/>
        public bool printed {
            get {
                return this.printedField;
            }
            set {
                this.printedField = value;
                this.RaisePropertyChanged("printed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool printedSpecified {
            get {
                return this.printedFieldSpecified;
            }
            set {
                this.printedFieldSpecified = value;
                this.RaisePropertyChanged("printedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("mailing", IsNullable=false)]
        public prepareRequestMailing[] mailings {
            get {
                return this.mailingsField;
            }
            set {
                this.mailingsField = value;
                this.RaisePropertyChanged("mailings");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.zelenaposta.sk/api/mailing")]
    public partial class prepareRequestMailing : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uiz1Field;
        
        private string uiz2Field;
        
        private addressType addressField;
        
        /// <remarks/>
        public string uiz1 {
            get {
                return this.uiz1Field;
            }
            set {
                this.uiz1Field = value;
                this.RaisePropertyChanged("uiz1");
            }
        }
        
        /// <remarks/>
        public string uiz2 {
            get {
                return this.uiz2Field;
            }
            set {
                this.uiz2Field = value;
                this.RaisePropertyChanged("uiz2");
            }
        }
        
        /// <remarks/>
        public addressType address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.zelenaposta.sk/api/mailing")]
    public partial class prepareResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private prepareResponseMailing[] mailingsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("mailing", IsNullable=false)]
        public prepareResponseMailing[] mailings {
            get {
                return this.mailingsField;
            }
            set {
                this.mailingsField = value;
                this.RaisePropertyChanged("mailings");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.zelenaposta.sk/api/mailing")]
    public partial class prepareResponseMailing : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uidField;
        
        private string pinField;
        
        private bool acceptsEmailsField;
        
        private bool acceptsEmailsFieldSpecified;
        
        /// <remarks/>
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
                this.RaisePropertyChanged("uid");
            }
        }
        
        /// <remarks/>
        public string pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
                this.RaisePropertyChanged("pin");
            }
        }
        
        /// <remarks/>
        public bool acceptsEmails {
            get {
                return this.acceptsEmailsField;
            }
            set {
                this.acceptsEmailsField = value;
                this.RaisePropertyChanged("acceptsEmails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool acceptsEmailsSpecified {
            get {
                return this.acceptsEmailsFieldSpecified;
            }
            set {
                this.acceptsEmailsFieldSpecified = value;
                this.RaisePropertyChanged("acceptsEmailsSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class prepareRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.zelenaposta.sk/api/mailing", Order=0)]
        public Cora.CommIss.Iss.ZelenaPostaRequireClient.prepareRequest prepareRequest;
        
        public prepareRequest1() {
        }
        
        public prepareRequest1(Cora.CommIss.Iss.ZelenaPostaRequireClient.prepareRequest prepareRequest) {
            this.prepareRequest = prepareRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class prepareResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.zelenaposta.sk/api/mailing", Order=0)]
        public Cora.CommIss.Iss.ZelenaPostaRequireClient.prepareResponse prepareResponse;
        
        public prepareResponse1() {
        }
        
        public prepareResponse1(Cora.CommIss.Iss.ZelenaPostaRequireClient.prepareResponse prepareResponse) {
            this.prepareResponse = prepareResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.zelenaposta.sk/api/mailing")]
    public partial class sendRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string titleField;
        
        private sendRequestMailing[] mailingsField;
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("mailing", IsNullable=false)]
        public sendRequestMailing[] mailings {
            get {
                return this.mailingsField;
            }
            set {
                this.mailingsField = value;
                this.RaisePropertyChanged("mailings");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.zelenaposta.sk/api/mailing")]
    public partial class sendRequestMailing : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string productField;
        
        private string correspondenceField;
        
        private string envelopeField;
        
        private string printingField;
        
        private bool duplexField;
        
        private bool duplexFieldSpecified;
        
        private string uiz1Field;
        
        private string uiz2Field;
        
        private string uidField;
        
        private string pinField;
        
        private string deliveryConfirmationTextField;
        
        private string customIdField;
        
        private sendRequestMailingDocument[] documentsField;
        
        private addressType recipientField;
        
        private addressType senderField;
        
        private addressType addressField;
        
        /// <remarks/>
        public string product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
                this.RaisePropertyChanged("product");
            }
        }
        
        /// <remarks/>
        public string correspondence {
            get {
                return this.correspondenceField;
            }
            set {
                this.correspondenceField = value;
                this.RaisePropertyChanged("correspondence");
            }
        }
        
        /// <remarks/>
        public string envelope {
            get {
                return this.envelopeField;
            }
            set {
                this.envelopeField = value;
                this.RaisePropertyChanged("envelope");
            }
        }
        
        /// <remarks/>
        public string printing {
            get {
                return this.printingField;
            }
            set {
                this.printingField = value;
                this.RaisePropertyChanged("printing");
            }
        }
        
        /// <remarks/>
        public bool duplex {
            get {
                return this.duplexField;
            }
            set {
                this.duplexField = value;
                this.RaisePropertyChanged("duplex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool duplexSpecified {
            get {
                return this.duplexFieldSpecified;
            }
            set {
                this.duplexFieldSpecified = value;
                this.RaisePropertyChanged("duplexSpecified");
            }
        }
        
        /// <remarks/>
        public string uiz1 {
            get {
                return this.uiz1Field;
            }
            set {
                this.uiz1Field = value;
                this.RaisePropertyChanged("uiz1");
            }
        }
        
        /// <remarks/>
        public string uiz2 {
            get {
                return this.uiz2Field;
            }
            set {
                this.uiz2Field = value;
                this.RaisePropertyChanged("uiz2");
            }
        }
        
        /// <remarks/>
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
                this.RaisePropertyChanged("uid");
            }
        }
        
        /// <remarks/>
        public string pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
                this.RaisePropertyChanged("pin");
            }
        }
        
        /// <remarks/>
        public string deliveryConfirmationText {
            get {
                return this.deliveryConfirmationTextField;
            }
            set {
                this.deliveryConfirmationTextField = value;
                this.RaisePropertyChanged("deliveryConfirmationText");
            }
        }
        
        /// <remarks/>
        public string customId {
            get {
                return this.customIdField;
            }
            set {
                this.customIdField = value;
                this.RaisePropertyChanged("customId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("document", IsNullable=false)]
        public sendRequestMailingDocument[] documents {
            get {
                return this.documentsField;
            }
            set {
                this.documentsField = value;
                this.RaisePropertyChanged("documents");
            }
        }
        
        /// <remarks/>
        public addressType recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
                this.RaisePropertyChanged("recipient");
            }
        }
        
        /// <remarks/>
        public addressType sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("sender");
            }
        }
        
        /// <remarks/>
        public addressType address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.zelenaposta.sk/api/mailing")]
    public partial class sendRequestMailingDocument : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] fileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
                this.RaisePropertyChanged("file");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.zelenaposta.sk/api/mailing")]
    public partial class sendResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string slotIdField;
        
        /// <remarks/>
        public string slotId {
            get {
                return this.slotIdField;
            }
            set {
                this.slotIdField = value;
                this.RaisePropertyChanged("slotId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.zelenaposta.sk/api/mailing", Order=0)]
        public Cora.CommIss.Iss.ZelenaPostaRequireClient.sendRequest sendRequest;
        
        public sendRequest1() {
        }
        
        public sendRequest1(Cora.CommIss.Iss.ZelenaPostaRequireClient.sendRequest sendRequest) {
            this.sendRequest = sendRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.zelenaposta.sk/api/mailing", Order=0)]
        public Cora.CommIss.Iss.ZelenaPostaRequireClient.sendResponse sendResponse;
        
        public sendResponse1() {
        }
        
        public sendResponse1(Cora.CommIss.Iss.ZelenaPostaRequireClient.sendResponse sendResponse) {
            this.sendResponse = sendResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.zelenaposta.sk/api/mailing")]
    public partial class getProductsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool freeProductsOnlyField;
        
        private bool freeProductsOnlyFieldSpecified;
        
        /// <remarks/>
        public bool freeProductsOnly {
            get {
                return this.freeProductsOnlyField;
            }
            set {
                this.freeProductsOnlyField = value;
                this.RaisePropertyChanged("freeProductsOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool freeProductsOnlySpecified {
            get {
                return this.freeProductsOnlyFieldSpecified;
            }
            set {
                this.freeProductsOnlyFieldSpecified = value;
                this.RaisePropertyChanged("freeProductsOnlySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.zelenaposta.sk/api/mailing")]
    public partial class getProductsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private getProductsResponseProduct[] productsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("product", IsNullable=false)]
        public getProductsResponseProduct[] products {
            get {
                return this.productsField;
            }
            set {
                this.productsField = value;
                this.RaisePropertyChanged("products");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.zelenaposta.sk/api/mailing")]
    public partial class getProductsResponseProduct : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string titleField;
        
        private int usageLeftField;
        
        private bool usageLeftFieldSpecified;
        
        private string descriptionField;
        
        private int pagesPerMailingField;
        
        private bool duplexField;
        
        private string correspondenceField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        public int usageLeft {
            get {
                return this.usageLeftField;
            }
            set {
                this.usageLeftField = value;
                this.RaisePropertyChanged("usageLeft");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usageLeftSpecified {
            get {
                return this.usageLeftFieldSpecified;
            }
            set {
                this.usageLeftFieldSpecified = value;
                this.RaisePropertyChanged("usageLeftSpecified");
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        public int pagesPerMailing {
            get {
                return this.pagesPerMailingField;
            }
            set {
                this.pagesPerMailingField = value;
                this.RaisePropertyChanged("pagesPerMailing");
            }
        }
        
        /// <remarks/>
        public bool duplex {
            get {
                return this.duplexField;
            }
            set {
                this.duplexField = value;
                this.RaisePropertyChanged("duplex");
            }
        }
        
        /// <remarks/>
        public string correspondence {
            get {
                return this.correspondenceField;
            }
            set {
                this.correspondenceField = value;
                this.RaisePropertyChanged("correspondence");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.zelenaposta.sk/api/mailing", Order=0)]
        public Cora.CommIss.Iss.ZelenaPostaRequireClient.getProductsRequest getProductsRequest;
        
        public getProductsRequest1() {
        }
        
        public getProductsRequest1(Cora.CommIss.Iss.ZelenaPostaRequireClient.getProductsRequest getProductsRequest) {
            this.getProductsRequest = getProductsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.zelenaposta.sk/api/mailing", Order=0)]
        public Cora.CommIss.Iss.ZelenaPostaRequireClient.getProductsResponse getProductsResponse;
        
        public getProductsResponse1() {
        }
        
        public getProductsResponse1(Cora.CommIss.Iss.ZelenaPostaRequireClient.getProductsResponse getProductsResponse) {
            this.getProductsResponse = getProductsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.zelenaposta.sk/api/mailing")]
    public partial class sendElectronicRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uiz1Field;
        
        private string uiz2Field;
        
        private string filenameField;
        
        /// <remarks/>
        public string uiz1 {
            get {
                return this.uiz1Field;
            }
            set {
                this.uiz1Field = value;
                this.RaisePropertyChanged("uiz1");
            }
        }
        
        /// <remarks/>
        public string uiz2 {
            get {
                return this.uiz2Field;
            }
            set {
                this.uiz2Field = value;
                this.RaisePropertyChanged("uiz2");
            }
        }
        
        /// <remarks/>
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
                this.RaisePropertyChanged("filename");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.zelenaposta.sk/api/mailing")]
    public partial class sendElectronicResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendElectronicRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.zelenaposta.sk/api/mailing", Order=0)]
        public Cora.CommIss.Iss.ZelenaPostaRequireClient.sendElectronicRequest sendElectronicRequest;
        
        public sendElectronicRequest1() {
        }
        
        public sendElectronicRequest1(Cora.CommIss.Iss.ZelenaPostaRequireClient.sendElectronicRequest sendElectronicRequest) {
            this.sendElectronicRequest = sendElectronicRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendElectronicResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.zelenaposta.sk/api/mailing", Order=0)]
        public Cora.CommIss.Iss.ZelenaPostaRequireClient.sendElectronicResponse sendElectronicResponse;
        
        public sendElectronicResponse1() {
        }
        
        public sendElectronicResponse1(Cora.CommIss.Iss.ZelenaPostaRequireClient.sendElectronicResponse sendElectronicResponse) {
            this.sendElectronicResponse = sendElectronicResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.zelenaposta.sk/api/mailing")]
    public partial class deleteRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int[] mailingsField;
        
        private int[] bundlesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("id", IsNullable=false)]
        public int[] mailings {
            get {
                return this.mailingsField;
            }
            set {
                this.mailingsField = value;
                this.RaisePropertyChanged("mailings");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("id", IsNullable=false)]
        public int[] bundles {
            get {
                return this.bundlesField;
            }
            set {
                this.bundlesField = value;
                this.RaisePropertyChanged("bundles");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.zelenaposta.sk/api/mailing")]
    public partial class deleteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.zelenaposta.sk/api/mailing", Order=0)]
        public Cora.CommIss.Iss.ZelenaPostaRequireClient.deleteRequest deleteRequest;
        
        public deleteRequest1() {
        }
        
        public deleteRequest1(Cora.CommIss.Iss.ZelenaPostaRequireClient.deleteRequest deleteRequest) {
            this.deleteRequest = deleteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.zelenaposta.sk/api/mailing", Order=0)]
        public Cora.CommIss.Iss.ZelenaPostaRequireClient.deleteResponse deleteResponse;
        
        public deleteResponse1() {
        }
        
        public deleteResponse1(Cora.CommIss.Iss.ZelenaPostaRequireClient.deleteResponse deleteResponse) {
            this.deleteResponse = deleteResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MailingChannel : Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailingClient : System.ServiceModel.ClientBase<Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing>, Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing {
        
        public MailingClient() {
        }
        
        public MailingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cora.CommIss.Iss.ZelenaPostaRequireClient.listResponse1 Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing.list(Cora.CommIss.Iss.ZelenaPostaRequireClient.listRequest1 request) {
            return base.Channel.list(request);
        }
        
        public Cora.CommIss.Iss.ZelenaPostaRequireClient.listResponse list(Cora.CommIss.Iss.ZelenaPostaRequireClient.listRequest listRequest) {
            Cora.CommIss.Iss.ZelenaPostaRequireClient.listRequest1 inValue = new Cora.CommIss.Iss.ZelenaPostaRequireClient.listRequest1();
            inValue.listRequest = listRequest;
            Cora.CommIss.Iss.ZelenaPostaRequireClient.listResponse1 retVal = ((Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing)(this)).list(inValue);
            return retVal.listResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaRequireClient.listResponse1> Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing.listAsync(Cora.CommIss.Iss.ZelenaPostaRequireClient.listRequest1 request) {
            return base.Channel.listAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaRequireClient.listResponse1> listAsync(Cora.CommIss.Iss.ZelenaPostaRequireClient.listRequest listRequest) {
            Cora.CommIss.Iss.ZelenaPostaRequireClient.listRequest1 inValue = new Cora.CommIss.Iss.ZelenaPostaRequireClient.listRequest1();
            inValue.listRequest = listRequest;
            return ((Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing)(this)).listAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cora.CommIss.Iss.ZelenaPostaRequireClient.prepareResponse1 Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing.prepare(Cora.CommIss.Iss.ZelenaPostaRequireClient.prepareRequest1 request) {
            return base.Channel.prepare(request);
        }
        
        public Cora.CommIss.Iss.ZelenaPostaRequireClient.prepareResponse prepare(Cora.CommIss.Iss.ZelenaPostaRequireClient.prepareRequest prepareRequest) {
            Cora.CommIss.Iss.ZelenaPostaRequireClient.prepareRequest1 inValue = new Cora.CommIss.Iss.ZelenaPostaRequireClient.prepareRequest1();
            inValue.prepareRequest = prepareRequest;
            Cora.CommIss.Iss.ZelenaPostaRequireClient.prepareResponse1 retVal = ((Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing)(this)).prepare(inValue);
            return retVal.prepareResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaRequireClient.prepareResponse1> Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing.prepareAsync(Cora.CommIss.Iss.ZelenaPostaRequireClient.prepareRequest1 request) {
            return base.Channel.prepareAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaRequireClient.prepareResponse1> prepareAsync(Cora.CommIss.Iss.ZelenaPostaRequireClient.prepareRequest prepareRequest) {
            Cora.CommIss.Iss.ZelenaPostaRequireClient.prepareRequest1 inValue = new Cora.CommIss.Iss.ZelenaPostaRequireClient.prepareRequest1();
            inValue.prepareRequest = prepareRequest;
            return ((Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing)(this)).prepareAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cora.CommIss.Iss.ZelenaPostaRequireClient.sendResponse1 Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing.send(Cora.CommIss.Iss.ZelenaPostaRequireClient.sendRequest1 request) {
            return base.Channel.send(request);
        }
        
        public Cora.CommIss.Iss.ZelenaPostaRequireClient.sendResponse send(Cora.CommIss.Iss.ZelenaPostaRequireClient.sendRequest sendRequest) {
            Cora.CommIss.Iss.ZelenaPostaRequireClient.sendRequest1 inValue = new Cora.CommIss.Iss.ZelenaPostaRequireClient.sendRequest1();
            inValue.sendRequest = sendRequest;
            Cora.CommIss.Iss.ZelenaPostaRequireClient.sendResponse1 retVal = ((Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing)(this)).send(inValue);
            return retVal.sendResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaRequireClient.sendResponse1> Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing.sendAsync(Cora.CommIss.Iss.ZelenaPostaRequireClient.sendRequest1 request) {
            return base.Channel.sendAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaRequireClient.sendResponse1> sendAsync(Cora.CommIss.Iss.ZelenaPostaRequireClient.sendRequest sendRequest) {
            Cora.CommIss.Iss.ZelenaPostaRequireClient.sendRequest1 inValue = new Cora.CommIss.Iss.ZelenaPostaRequireClient.sendRequest1();
            inValue.sendRequest = sendRequest;
            return ((Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing)(this)).sendAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cora.CommIss.Iss.ZelenaPostaRequireClient.getProductsResponse1 Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing.getProducts(Cora.CommIss.Iss.ZelenaPostaRequireClient.getProductsRequest1 request) {
            return base.Channel.getProducts(request);
        }
        
        public Cora.CommIss.Iss.ZelenaPostaRequireClient.getProductsResponse getProducts(Cora.CommIss.Iss.ZelenaPostaRequireClient.getProductsRequest getProductsRequest) {
            Cora.CommIss.Iss.ZelenaPostaRequireClient.getProductsRequest1 inValue = new Cora.CommIss.Iss.ZelenaPostaRequireClient.getProductsRequest1();
            inValue.getProductsRequest = getProductsRequest;
            Cora.CommIss.Iss.ZelenaPostaRequireClient.getProductsResponse1 retVal = ((Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing)(this)).getProducts(inValue);
            return retVal.getProductsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaRequireClient.getProductsResponse1> Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing.getProductsAsync(Cora.CommIss.Iss.ZelenaPostaRequireClient.getProductsRequest1 request) {
            return base.Channel.getProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaRequireClient.getProductsResponse1> getProductsAsync(Cora.CommIss.Iss.ZelenaPostaRequireClient.getProductsRequest getProductsRequest) {
            Cora.CommIss.Iss.ZelenaPostaRequireClient.getProductsRequest1 inValue = new Cora.CommIss.Iss.ZelenaPostaRequireClient.getProductsRequest1();
            inValue.getProductsRequest = getProductsRequest;
            return ((Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing)(this)).getProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cora.CommIss.Iss.ZelenaPostaRequireClient.sendElectronicResponse1 Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing.sendElectronic(Cora.CommIss.Iss.ZelenaPostaRequireClient.sendElectronicRequest1 request) {
            return base.Channel.sendElectronic(request);
        }
        
        public Cora.CommIss.Iss.ZelenaPostaRequireClient.sendElectronicResponse sendElectronic(Cora.CommIss.Iss.ZelenaPostaRequireClient.sendElectronicRequest sendElectronicRequest) {
            Cora.CommIss.Iss.ZelenaPostaRequireClient.sendElectronicRequest1 inValue = new Cora.CommIss.Iss.ZelenaPostaRequireClient.sendElectronicRequest1();
            inValue.sendElectronicRequest = sendElectronicRequest;
            Cora.CommIss.Iss.ZelenaPostaRequireClient.sendElectronicResponse1 retVal = ((Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing)(this)).sendElectronic(inValue);
            return retVal.sendElectronicResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaRequireClient.sendElectronicResponse1> Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing.sendElectronicAsync(Cora.CommIss.Iss.ZelenaPostaRequireClient.sendElectronicRequest1 request) {
            return base.Channel.sendElectronicAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaRequireClient.sendElectronicResponse1> sendElectronicAsync(Cora.CommIss.Iss.ZelenaPostaRequireClient.sendElectronicRequest sendElectronicRequest) {
            Cora.CommIss.Iss.ZelenaPostaRequireClient.sendElectronicRequest1 inValue = new Cora.CommIss.Iss.ZelenaPostaRequireClient.sendElectronicRequest1();
            inValue.sendElectronicRequest = sendElectronicRequest;
            return ((Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing)(this)).sendElectronicAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cora.CommIss.Iss.ZelenaPostaRequireClient.deleteResponse1 Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing.delete(Cora.CommIss.Iss.ZelenaPostaRequireClient.deleteRequest1 request) {
            return base.Channel.delete(request);
        }
        
        public Cora.CommIss.Iss.ZelenaPostaRequireClient.deleteResponse delete(Cora.CommIss.Iss.ZelenaPostaRequireClient.deleteRequest deleteRequest) {
            Cora.CommIss.Iss.ZelenaPostaRequireClient.deleteRequest1 inValue = new Cora.CommIss.Iss.ZelenaPostaRequireClient.deleteRequest1();
            inValue.deleteRequest = deleteRequest;
            Cora.CommIss.Iss.ZelenaPostaRequireClient.deleteResponse1 retVal = ((Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing)(this)).delete(inValue);
            return retVal.deleteResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaRequireClient.deleteResponse1> Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing.deleteAsync(Cora.CommIss.Iss.ZelenaPostaRequireClient.deleteRequest1 request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaRequireClient.deleteResponse1> deleteAsync(Cora.CommIss.Iss.ZelenaPostaRequireClient.deleteRequest deleteRequest) {
            Cora.CommIss.Iss.ZelenaPostaRequireClient.deleteRequest1 inValue = new Cora.CommIss.Iss.ZelenaPostaRequireClient.deleteRequest1();
            inValue.deleteRequest = deleteRequest;
            return ((Cora.CommIss.Iss.ZelenaPostaRequireClient.Mailing)(this)).deleteAsync(inValue);
        }
    }
}
