//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cora.CommIss.Iss.EVOClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interfaces.ditec.sk/", ConfigurationName="EVOClient.IPoskytnutieUdajovOvozidleAdrzitelovi")]
    public interface IPoskytnutieUdajovOvozidleAdrzitelovi {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Cora.CommIss.Iss.EVOClient.wsPoskytnutieUdajovOvozidleAdrziteloviResponse wsPoskytnutieUdajovOvozidleAdrzitelovi(Cora.CommIss.Iss.EVOClient.wsPoskytnutieUdajovOvozidleAdrziteloviRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.EVOClient.wsPoskytnutieUdajovOvozidleAdrziteloviResponse> wsPoskytnutieUdajovOvozidleAdrziteloviAsync(Cora.CommIss.Iss.EVOClient.wsPoskytnutieUdajovOvozidleAdrziteloviRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces.ditec.sk/")]
    public partial class vozidloRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vinField;
        
        private string evidencneCisloField;
        
        private string epField;
        
        private string tdField;
        
        private string dovodLustracieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string vin {
            get {
                return this.vinField;
            }
            set {
                this.vinField = value;
                this.RaisePropertyChanged("vin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string evidencneCislo {
            get {
                return this.evidencneCisloField;
            }
            set {
                this.evidencneCisloField = value;
                this.RaisePropertyChanged("evidencneCislo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ep {
            get {
                return this.epField;
            }
            set {
                this.epField = value;
                this.RaisePropertyChanged("ep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string td {
            get {
                return this.tdField;
            }
            set {
                this.tdField = value;
                this.RaisePropertyChanged("td");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string dovodLustracie {
            get {
                return this.dovodLustracieField;
            }
            set {
                this.dovodLustracieField = value;
                this.RaisePropertyChanged("dovodLustracie");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces.ditec.sk/")]
    public partial class pobytSidloBuducehoDrzitela : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string buduciDrzitelPobytTypPobytuField;
        
        private string buduciDrzitelPobytOkresField;
        
        private string buduciDrzitelPobytObecField;
        
        private string buduciDrzitelPobytUlicaField;
        
        private string buduciDrzitelPobytOrientacneCisloField;
        
        private string buduciDrzitelPobytSupisneCisloField;
        
        private string buduciDrzitelAdresaMimoSRField;
        
        private string buduciDrzitelStatAdresyMimoSRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BuduciDrzitelPobytTypPobytu {
            get {
                return this.buduciDrzitelPobytTypPobytuField;
            }
            set {
                this.buduciDrzitelPobytTypPobytuField = value;
                this.RaisePropertyChanged("BuduciDrzitelPobytTypPobytu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string BuduciDrzitelPobytOkres {
            get {
                return this.buduciDrzitelPobytOkresField;
            }
            set {
                this.buduciDrzitelPobytOkresField = value;
                this.RaisePropertyChanged("BuduciDrzitelPobytOkres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string BuduciDrzitelPobytObec {
            get {
                return this.buduciDrzitelPobytObecField;
            }
            set {
                this.buduciDrzitelPobytObecField = value;
                this.RaisePropertyChanged("BuduciDrzitelPobytObec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BuduciDrzitelPobytUlica {
            get {
                return this.buduciDrzitelPobytUlicaField;
            }
            set {
                this.buduciDrzitelPobytUlicaField = value;
                this.RaisePropertyChanged("BuduciDrzitelPobytUlica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string BuduciDrzitelPobytOrientacneCislo {
            get {
                return this.buduciDrzitelPobytOrientacneCisloField;
            }
            set {
                this.buduciDrzitelPobytOrientacneCisloField = value;
                this.RaisePropertyChanged("BuduciDrzitelPobytOrientacneCislo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string BuduciDrzitelPobytSupisneCislo {
            get {
                return this.buduciDrzitelPobytSupisneCisloField;
            }
            set {
                this.buduciDrzitelPobytSupisneCisloField = value;
                this.RaisePropertyChanged("BuduciDrzitelPobytSupisneCislo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string BuduciDrzitelAdresaMimoSR {
            get {
                return this.buduciDrzitelAdresaMimoSRField;
            }
            set {
                this.buduciDrzitelAdresaMimoSRField = value;
                this.RaisePropertyChanged("BuduciDrzitelAdresaMimoSR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string BuduciDrzitelStatAdresyMimoSR {
            get {
                return this.buduciDrzitelStatAdresyMimoSRField;
            }
            set {
                this.buduciDrzitelStatAdresyMimoSRField = value;
                this.RaisePropertyChanged("BuduciDrzitelStatAdresyMimoSR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces.ditec.sk/")]
    public partial class buduciDrzitel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string buduciDrzitelMenoField;
        
        private string buduciDrzitelPriezviskoField;
        
        private System.DateTime buduciDrzitelDatumNarodeniaField;
        
        private bool buduciDrzitelDatumNarodeniaFieldSpecified;
        
        private string buduciDrzitelRodneCisloField;
        
        private string buduciDrzitelNazovField;
        
        private string buduciDrzitelICOField;
        
        private pobytSidloBuducehoDrzitela buduciDrzitelPobytField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BuduciDrzitelMeno {
            get {
                return this.buduciDrzitelMenoField;
            }
            set {
                this.buduciDrzitelMenoField = value;
                this.RaisePropertyChanged("BuduciDrzitelMeno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string BuduciDrzitelPriezvisko {
            get {
                return this.buduciDrzitelPriezviskoField;
            }
            set {
                this.buduciDrzitelPriezviskoField = value;
                this.RaisePropertyChanged("BuduciDrzitelPriezvisko");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime BuduciDrzitelDatumNarodenia {
            get {
                return this.buduciDrzitelDatumNarodeniaField;
            }
            set {
                this.buduciDrzitelDatumNarodeniaField = value;
                this.RaisePropertyChanged("BuduciDrzitelDatumNarodenia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BuduciDrzitelDatumNarodeniaSpecified {
            get {
                return this.buduciDrzitelDatumNarodeniaFieldSpecified;
            }
            set {
                this.buduciDrzitelDatumNarodeniaFieldSpecified = value;
                this.RaisePropertyChanged("BuduciDrzitelDatumNarodeniaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BuduciDrzitelRodneCislo {
            get {
                return this.buduciDrzitelRodneCisloField;
            }
            set {
                this.buduciDrzitelRodneCisloField = value;
                this.RaisePropertyChanged("BuduciDrzitelRodneCislo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string BuduciDrzitelNazov {
            get {
                return this.buduciDrzitelNazovField;
            }
            set {
                this.buduciDrzitelNazovField = value;
                this.RaisePropertyChanged("BuduciDrzitelNazov");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string BuduciDrzitelICO {
            get {
                return this.buduciDrzitelICOField;
            }
            set {
                this.buduciDrzitelICOField = value;
                this.RaisePropertyChanged("BuduciDrzitelICO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public pobytSidloBuducehoDrzitela BuduciDrzitelPobyt {
            get {
                return this.buduciDrzitelPobytField;
            }
            set {
                this.buduciDrzitelPobytField = value;
                this.RaisePropertyChanged("BuduciDrzitelPobyt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces.ditec.sk/")]
    public partial class pobytSidloDrzitela : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string drzitelPobytTypPobytuField;
        
        private string drzitelPobytOkresField;
        
        private string drzitelPobytObecField;
        
        private string drzitelPobytUlicaField;
        
        private string drzitelPobytOrientacneCisloField;
        
        private string drzitelPobytSupisneCisloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DrzitelPobytTypPobytu {
            get {
                return this.drzitelPobytTypPobytuField;
            }
            set {
                this.drzitelPobytTypPobytuField = value;
                this.RaisePropertyChanged("DrzitelPobytTypPobytu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DrzitelPobytOkres {
            get {
                return this.drzitelPobytOkresField;
            }
            set {
                this.drzitelPobytOkresField = value;
                this.RaisePropertyChanged("DrzitelPobytOkres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DrzitelPobytObec {
            get {
                return this.drzitelPobytObecField;
            }
            set {
                this.drzitelPobytObecField = value;
                this.RaisePropertyChanged("DrzitelPobytObec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DrzitelPobytUlica {
            get {
                return this.drzitelPobytUlicaField;
            }
            set {
                this.drzitelPobytUlicaField = value;
                this.RaisePropertyChanged("DrzitelPobytUlica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DrzitelPobytOrientacneCislo {
            get {
                return this.drzitelPobytOrientacneCisloField;
            }
            set {
                this.drzitelPobytOrientacneCisloField = value;
                this.RaisePropertyChanged("DrzitelPobytOrientacneCislo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string DrzitelPobytSupisneCislo {
            get {
                return this.drzitelPobytSupisneCisloField;
            }
            set {
                this.drzitelPobytSupisneCisloField = value;
                this.RaisePropertyChanged("DrzitelPobytSupisneCislo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces.ditec.sk/")]
    public partial class drzitel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string drzitelMenoField;
        
        private string drzitelPriezviskoField;
        
        private System.DateTime drzitelDatumNarodeniaField;
        
        private bool drzitelDatumNarodeniaFieldSpecified;
        
        private string drzitelRodneCisloField;
        
        private string drzitelNazovField;
        
        private string drzitelICOField;
        
        private pobytSidloDrzitela drzitelPobytField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DrzitelMeno {
            get {
                return this.drzitelMenoField;
            }
            set {
                this.drzitelMenoField = value;
                this.RaisePropertyChanged("DrzitelMeno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DrzitelPriezvisko {
            get {
                return this.drzitelPriezviskoField;
            }
            set {
                this.drzitelPriezviskoField = value;
                this.RaisePropertyChanged("DrzitelPriezvisko");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime DrzitelDatumNarodenia {
            get {
                return this.drzitelDatumNarodeniaField;
            }
            set {
                this.drzitelDatumNarodeniaField = value;
                this.RaisePropertyChanged("DrzitelDatumNarodenia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DrzitelDatumNarodeniaSpecified {
            get {
                return this.drzitelDatumNarodeniaFieldSpecified;
            }
            set {
                this.drzitelDatumNarodeniaFieldSpecified = value;
                this.RaisePropertyChanged("DrzitelDatumNarodeniaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DrzitelRodneCislo {
            get {
                return this.drzitelRodneCisloField;
            }
            set {
                this.drzitelRodneCisloField = value;
                this.RaisePropertyChanged("DrzitelRodneCislo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DrzitelNazov {
            get {
                return this.drzitelNazovField;
            }
            set {
                this.drzitelNazovField = value;
                this.RaisePropertyChanged("DrzitelNazov");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string DrzitelICO {
            get {
                return this.drzitelICOField;
            }
            set {
                this.drzitelICOField = value;
                this.RaisePropertyChanged("DrzitelICO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public pobytSidloDrzitela DrzitelPobyt {
            get {
                return this.drzitelPobytField;
            }
            set {
                this.drzitelPobytField = value;
                this.RaisePropertyChanged("DrzitelPobyt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces.ditec.sk/")]
    public partial class vozidlo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vINField;
        
        private string evidencneCisloField;
        
        private string kategoriaVozidlaField;
        
        private string druhVozidlaField;
        
        private string znackaField;
        
        private string farbaField;
        
        private string stavVozidlaField;
        
        private System.DateTime datumZmenyField;
        
        private bool datumZmenyFieldSpecified;
        
        private drzitel drzitelField;
        
        private buduciDrzitel buduciDrzitelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VIN {
            get {
                return this.vINField;
            }
            set {
                this.vINField = value;
                this.RaisePropertyChanged("VIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string EvidencneCislo {
            get {
                return this.evidencneCisloField;
            }
            set {
                this.evidencneCisloField = value;
                this.RaisePropertyChanged("EvidencneCislo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string KategoriaVozidla {
            get {
                return this.kategoriaVozidlaField;
            }
            set {
                this.kategoriaVozidlaField = value;
                this.RaisePropertyChanged("KategoriaVozidla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DruhVozidla {
            get {
                return this.druhVozidlaField;
            }
            set {
                this.druhVozidlaField = value;
                this.RaisePropertyChanged("DruhVozidla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Znacka {
            get {
                return this.znackaField;
            }
            set {
                this.znackaField = value;
                this.RaisePropertyChanged("Znacka");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Farba {
            get {
                return this.farbaField;
            }
            set {
                this.farbaField = value;
                this.RaisePropertyChanged("Farba");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string StavVozidla {
            get {
                return this.stavVozidlaField;
            }
            set {
                this.stavVozidlaField = value;
                this.RaisePropertyChanged("StavVozidla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime DatumZmeny {
            get {
                return this.datumZmenyField;
            }
            set {
                this.datumZmenyField = value;
                this.RaisePropertyChanged("DatumZmeny");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatumZmenySpecified {
            get {
                return this.datumZmenyFieldSpecified;
            }
            set {
                this.datumZmenyFieldSpecified = value;
                this.RaisePropertyChanged("DatumZmenySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public drzitel Drzitel {
            get {
                return this.drzitelField;
            }
            set {
                this.drzitelField = value;
                this.RaisePropertyChanged("Drzitel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public buduciDrzitel BuduciDrzitel {
            get {
                return this.buduciDrzitelField;
            }
            set {
                this.buduciDrzitelField = value;
                this.RaisePropertyChanged("BuduciDrzitel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces.ditec.sk/")]
    public partial class message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces.ditec.sk/")]
    public partial class poskytnutieUdajovOvozidleAdrziteloviResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private message msgField;
        
        private vozidlo vozidloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public message msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public vozidlo vozidlo {
            get {
                return this.vozidloField;
            }
            set {
                this.vozidloField = value;
                this.RaisePropertyChanged("vozidlo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsPoskytnutieUdajovOvozidleAdrzitelovi", WrapperNamespace="http://interfaces.ditec.sk/", IsWrapped=true)]
    public partial class wsPoskytnutieUdajovOvozidleAdrziteloviRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interfaces.ditec.sk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Cora.CommIss.Iss.EVOClient.vozidloRequest arg0;
        
        public wsPoskytnutieUdajovOvozidleAdrziteloviRequest() {
        }
        
        public wsPoskytnutieUdajovOvozidleAdrziteloviRequest(Cora.CommIss.Iss.EVOClient.vozidloRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsPoskytnutieUdajovOvozidleAdrziteloviResponse", WrapperNamespace="http://interfaces.ditec.sk/", IsWrapped=true)]
    public partial class wsPoskytnutieUdajovOvozidleAdrziteloviResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interfaces.ditec.sk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Cora.CommIss.Iss.EVOClient.poskytnutieUdajovOvozidleAdrziteloviResponse @return;
        
        public wsPoskytnutieUdajovOvozidleAdrziteloviResponse() {
        }
        
        public wsPoskytnutieUdajovOvozidleAdrziteloviResponse(Cora.CommIss.Iss.EVOClient.poskytnutieUdajovOvozidleAdrziteloviResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPoskytnutieUdajovOvozidleAdrziteloviChannel : Cora.CommIss.Iss.EVOClient.IPoskytnutieUdajovOvozidleAdrzitelovi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PoskytnutieUdajovOvozidleAdrziteloviClient : System.ServiceModel.ClientBase<Cora.CommIss.Iss.EVOClient.IPoskytnutieUdajovOvozidleAdrzitelovi>, Cora.CommIss.Iss.EVOClient.IPoskytnutieUdajovOvozidleAdrzitelovi {
        
        public PoskytnutieUdajovOvozidleAdrziteloviClient() {
        }
        
        public PoskytnutieUdajovOvozidleAdrziteloviClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PoskytnutieUdajovOvozidleAdrziteloviClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PoskytnutieUdajovOvozidleAdrziteloviClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PoskytnutieUdajovOvozidleAdrziteloviClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cora.CommIss.Iss.EVOClient.wsPoskytnutieUdajovOvozidleAdrziteloviResponse Cora.CommIss.Iss.EVOClient.IPoskytnutieUdajovOvozidleAdrzitelovi.wsPoskytnutieUdajovOvozidleAdrzitelovi(Cora.CommIss.Iss.EVOClient.wsPoskytnutieUdajovOvozidleAdrziteloviRequest request) {
            return base.Channel.wsPoskytnutieUdajovOvozidleAdrzitelovi(request);
        }
        
        public Cora.CommIss.Iss.EVOClient.poskytnutieUdajovOvozidleAdrziteloviResponse wsPoskytnutieUdajovOvozidleAdrzitelovi(Cora.CommIss.Iss.EVOClient.vozidloRequest arg0) {
            Cora.CommIss.Iss.EVOClient.wsPoskytnutieUdajovOvozidleAdrziteloviRequest inValue = new Cora.CommIss.Iss.EVOClient.wsPoskytnutieUdajovOvozidleAdrziteloviRequest();
            inValue.arg0 = arg0;
            Cora.CommIss.Iss.EVOClient.wsPoskytnutieUdajovOvozidleAdrziteloviResponse retVal = ((Cora.CommIss.Iss.EVOClient.IPoskytnutieUdajovOvozidleAdrzitelovi)(this)).wsPoskytnutieUdajovOvozidleAdrzitelovi(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.EVOClient.wsPoskytnutieUdajovOvozidleAdrziteloviResponse> Cora.CommIss.Iss.EVOClient.IPoskytnutieUdajovOvozidleAdrzitelovi.wsPoskytnutieUdajovOvozidleAdrziteloviAsync(Cora.CommIss.Iss.EVOClient.wsPoskytnutieUdajovOvozidleAdrziteloviRequest request) {
            return base.Channel.wsPoskytnutieUdajovOvozidleAdrziteloviAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.EVOClient.wsPoskytnutieUdajovOvozidleAdrziteloviResponse> wsPoskytnutieUdajovOvozidleAdrziteloviAsync(Cora.CommIss.Iss.EVOClient.vozidloRequest arg0) {
            Cora.CommIss.Iss.EVOClient.wsPoskytnutieUdajovOvozidleAdrziteloviRequest inValue = new Cora.CommIss.Iss.EVOClient.wsPoskytnutieUdajovOvozidleAdrziteloviRequest();
            inValue.arg0 = arg0;
            return ((Cora.CommIss.Iss.EVOClient.IPoskytnutieUdajovOvozidleAdrzitelovi)(this)).wsPoskytnutieUdajovOvozidleAdrziteloviAsync(inValue);
        }
    }
}
