//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cora.CommIss.Iss.DoveraSystemClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DajOznamyDZPVstup", Namespace="http://b2b.dovera.sk")]
    [System.SerializableAttribute()]
    public partial class DajOznamyDZPVstup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Cora.CommIss.Iss.DoveraSystemClient.APITokenPouzivatela TokenPouzivatelaField;
        
        private Cora.CommIss.Iss.DoveraSystemClient.APIFormaVystup FormaVystupField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Cora.CommIss.Iss.DoveraSystemClient.APITokenPouzivatela TokenPouzivatela {
            get {
                return this.TokenPouzivatelaField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenPouzivatelaField, value) != true)) {
                    this.TokenPouzivatelaField = value;
                    this.RaisePropertyChanged("TokenPouzivatela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public Cora.CommIss.Iss.DoveraSystemClient.APIFormaVystup FormaVystup {
            get {
                return this.FormaVystupField;
            }
            set {
                if ((this.FormaVystupField.Equals(value) != true)) {
                    this.FormaVystupField = value;
                    this.RaisePropertyChanged("FormaVystup");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APITokenPouzivatela", Namespace="http://schemas.dovera.sk/b2b/types")]
    [System.SerializableAttribute()]
    public partial class APITokenPouzivatela : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string LoginField;
        
        private string DodavatelSWField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodNZField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodVZField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnikatnyKodPLAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CasovyLimitVolaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ICOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string DodavatelSW {
            get {
                return this.DodavatelSWField;
            }
            set {
                if ((object.ReferenceEquals(this.DodavatelSWField, value) != true)) {
                    this.DodavatelSWField = value;
                    this.RaisePropertyChanged("DodavatelSW");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string KodNZ {
            get {
                return this.KodNZField;
            }
            set {
                if ((object.ReferenceEquals(this.KodNZField, value) != true)) {
                    this.KodNZField = value;
                    this.RaisePropertyChanged("KodNZ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string KodVZ {
            get {
                return this.KodVZField;
            }
            set {
                if ((object.ReferenceEquals(this.KodVZField, value) != true)) {
                    this.KodVZField = value;
                    this.RaisePropertyChanged("KodVZ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string VS {
            get {
                return this.VSField;
            }
            set {
                if ((object.ReferenceEquals(this.VSField, value) != true)) {
                    this.VSField = value;
                    this.RaisePropertyChanged("VS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string UnikatnyKodPLA {
            get {
                return this.UnikatnyKodPLAField;
            }
            set {
                if ((object.ReferenceEquals(this.UnikatnyKodPLAField, value) != true)) {
                    this.UnikatnyKodPLAField = value;
                    this.RaisePropertyChanged("UnikatnyKodPLA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int CasovyLimitVolania {
            get {
                return this.CasovyLimitVolaniaField;
            }
            set {
                if ((this.CasovyLimitVolaniaField.Equals(value) != true)) {
                    this.CasovyLimitVolaniaField = value;
                    this.RaisePropertyChanged("CasovyLimitVolania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ICO {
            get {
                return this.ICOField;
            }
            set {
                if ((object.ReferenceEquals(this.ICOField, value) != true)) {
                    this.ICOField = value;
                    this.RaisePropertyChanged("ICO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIFormaVystup", Namespace="http://schemas.dovera.sk/b2b/types")]
    public enum APIFormaVystup : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        API = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PDF = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TAB = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DajOznamyDZPVystup", Namespace="http://b2b.dovera.sk")]
    [System.SerializableAttribute()]
    public partial class DajOznamyDZPVystup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] OznamDZPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cora.CommIss.Iss.DoveraSystemClient.APIDokument DokumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cora.CommIss.Iss.DoveraSystemClient.ArrayOfOznamDZPTabAPIOznamDZPTab OznamyDZPTabField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] OznamDZP {
            get {
                return this.OznamDZPField;
            }
            set {
                if ((object.ReferenceEquals(this.OznamDZPField, value) != true)) {
                    this.OznamDZPField = value;
                    this.RaisePropertyChanged("OznamDZP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Cora.CommIss.Iss.DoveraSystemClient.APIDokument Dokument {
            get {
                return this.DokumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DokumentField, value) != true)) {
                    this.DokumentField = value;
                    this.RaisePropertyChanged("Dokument");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Cora.CommIss.Iss.DoveraSystemClient.ArrayOfOznamDZPTabAPIOznamDZPTab OznamyDZPTab {
            get {
                return this.OznamyDZPTabField;
            }
            set {
                if ((object.ReferenceEquals(this.OznamyDZPTabField, value) != true)) {
                    this.OznamyDZPTabField = value;
                    this.RaisePropertyChanged("OznamyDZPTab");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIDokument", Namespace="http://schemas.dovera.sk/b2b/types")]
    [System.SerializableAttribute()]
    public partial class APIDokument : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazovDokumentuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ObsahField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool KomprimovanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoznamkaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NazovDokumentu {
            get {
                return this.NazovDokumentuField;
            }
            set {
                if ((object.ReferenceEquals(this.NazovDokumentuField, value) != true)) {
                    this.NazovDokumentuField = value;
                    this.RaisePropertyChanged("NazovDokumentu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Typ {
            get {
                return this.TypField;
            }
            set {
                if ((object.ReferenceEquals(this.TypField, value) != true)) {
                    this.TypField = value;
                    this.RaisePropertyChanged("Typ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] Obsah {
            get {
                return this.ObsahField;
            }
            set {
                if ((object.ReferenceEquals(this.ObsahField, value) != true)) {
                    this.ObsahField = value;
                    this.RaisePropertyChanged("Obsah");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool Komprimovany {
            get {
                return this.KomprimovanyField;
            }
            set {
                if ((this.KomprimovanyField.Equals(value) != true)) {
                    this.KomprimovanyField = value;
                    this.RaisePropertyChanged("Komprimovany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Poznamka {
            get {
                return this.PoznamkaField;
            }
            set {
                if ((object.ReferenceEquals(this.PoznamkaField, value) != true)) {
                    this.PoznamkaField = value;
                    this.RaisePropertyChanged("Poznamka");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfOznamDZPTabAPIOznamDZPTab", Namespace="http://b2b.dovera.sk", ItemName="OznamDZPTab")]
    [System.SerializableAttribute()]
    public class ArrayOfOznamDZPTabAPIOznamDZPTab : System.Collections.Generic.List<Cora.CommIss.Iss.DoveraSystemClient.APIOznamDZPTab> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIOznamDZPTab", Namespace="http://schemas.dovera.sk/b2b/types")]
    [System.SerializableAttribute()]
    public partial class APIOznamDZPTab : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string TypOznamuField;
        
        private string RolaField;
        
        private string NadpisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PopisField;
        
        private System.DateTime ZaciatokField;
        
        private System.DateTime KoniecField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string TypOznamu {
            get {
                return this.TypOznamuField;
            }
            set {
                if ((object.ReferenceEquals(this.TypOznamuField, value) != true)) {
                    this.TypOznamuField = value;
                    this.RaisePropertyChanged("TypOznamu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string Rola {
            get {
                return this.RolaField;
            }
            set {
                if ((object.ReferenceEquals(this.RolaField, value) != true)) {
                    this.RolaField = value;
                    this.RaisePropertyChanged("Rola");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string Nadpis {
            get {
                return this.NadpisField;
            }
            set {
                if ((object.ReferenceEquals(this.NadpisField, value) != true)) {
                    this.NadpisField = value;
                    this.RaisePropertyChanged("Nadpis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Popis {
            get {
                return this.PopisField;
            }
            set {
                if ((object.ReferenceEquals(this.PopisField, value) != true)) {
                    this.PopisField = value;
                    this.RaisePropertyChanged("Popis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime Zaciatok {
            get {
                return this.ZaciatokField;
            }
            set {
                if ((this.ZaciatokField.Equals(value) != true)) {
                    this.ZaciatokField = value;
                    this.RaisePropertyChanged("Zaciatok");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime Koniec {
            get {
                return this.KoniecField;
            }
            set {
                if ((this.KoniecField.Equals(value) != true)) {
                    this.KoniecField = value;
                    this.RaisePropertyChanged("Koniec");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DajPrihlasovaciTokenVstup", Namespace="http://b2b.dovera.sk")]
    [System.SerializableAttribute()]
    public partial class DajPrihlasovaciTokenVstup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Cora.CommIss.Iss.DoveraSystemClient.APITokenPouzivatela TokenPouzivatelaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Cora.CommIss.Iss.DoveraSystemClient.APITokenPouzivatela TokenPouzivatela {
            get {
                return this.TokenPouzivatelaField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenPouzivatelaField, value) != true)) {
                    this.TokenPouzivatelaField = value;
                    this.RaisePropertyChanged("TokenPouzivatela");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DajPrihlasovaciTokenVystup", Namespace="http://b2b.dovera.sk")]
    [System.SerializableAttribute()]
    public partial class DajPrihlasovaciTokenVystup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrihlasovaciTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PlatnostTokenuDoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PrihlasovaciToken {
            get {
                return this.PrihlasovaciTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.PrihlasovaciTokenField, value) != true)) {
                    this.PrihlasovaciTokenField = value;
                    this.RaisePropertyChanged("PrihlasovaciToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime PlatnostTokenuDo {
            get {
                return this.PlatnostTokenuDoField;
            }
            set {
                if ((this.PlatnostTokenuDoField.Equals(value) != true)) {
                    this.PlatnostTokenuDoField = value;
                    this.RaisePropertyChanged("PlatnostTokenuDo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DajStavSystemuVstup", Namespace="http://b2b.dovera.sk")]
    [System.SerializableAttribute()]
    public partial class DajStavSystemuVstup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Cora.CommIss.Iss.DoveraSystemClient.APITokenPouzivatela TokenPouzivatelaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Cora.CommIss.Iss.DoveraSystemClient.APITokenPouzivatela TokenPouzivatela {
            get {
                return this.TokenPouzivatelaField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenPouzivatelaField, value) != true)) {
                    this.TokenPouzivatelaField = value;
                    this.RaisePropertyChanged("TokenPouzivatela");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DajStavSystemuVystup", Namespace="http://b2b.dovera.sk")]
    [System.SerializableAttribute()]
    public partial class DajStavSystemuVystup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool JeOnlineField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool JeOnline {
            get {
                return this.JeOnlineField;
            }
            set {
                if ((this.JeOnlineField.Equals(value) != true)) {
                    this.JeOnlineField = value;
                    this.RaisePropertyChanged("JeOnline");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrihlasenieTokenomVstup", Namespace="http://b2b.dovera.sk")]
    [System.SerializableAttribute()]
    public partial class PrihlasenieTokenomVstup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Cora.CommIss.Iss.DoveraSystemClient.APITokenPouzivatela TokenPouzivatelaField;
        
        private string PrihlasovaciTokenField;
        
        private string StrankaPoPrihlaseniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cora.CommIss.Iss.DoveraSystemClient.ArrayOfPolozkaAPIPrihlasenieFilter FilterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Cora.CommIss.Iss.DoveraSystemClient.APITokenPouzivatela TokenPouzivatela {
            get {
                return this.TokenPouzivatelaField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenPouzivatelaField, value) != true)) {
                    this.TokenPouzivatelaField = value;
                    this.RaisePropertyChanged("TokenPouzivatela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string PrihlasovaciToken {
            get {
                return this.PrihlasovaciTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.PrihlasovaciTokenField, value) != true)) {
                    this.PrihlasovaciTokenField = value;
                    this.RaisePropertyChanged("PrihlasovaciToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string StrankaPoPrihlaseni {
            get {
                return this.StrankaPoPrihlaseniField;
            }
            set {
                if ((object.ReferenceEquals(this.StrankaPoPrihlaseniField, value) != true)) {
                    this.StrankaPoPrihlaseniField = value;
                    this.RaisePropertyChanged("StrankaPoPrihlaseni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Cora.CommIss.Iss.DoveraSystemClient.ArrayOfPolozkaAPIPrihlasenieFilter Filter {
            get {
                return this.FilterField;
            }
            set {
                if ((object.ReferenceEquals(this.FilterField, value) != true)) {
                    this.FilterField = value;
                    this.RaisePropertyChanged("Filter");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfPolozkaAPIPrihlasenieFilter", Namespace="http://b2b.dovera.sk", ItemName="Polozka")]
    [System.SerializableAttribute()]
    public class ArrayOfPolozkaAPIPrihlasenieFilter : System.Collections.Generic.List<Cora.CommIss.Iss.DoveraSystemClient.APIPrihlasenieFilter> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIPrihlasenieFilter", Namespace="http://schemas.dovera.sk/b2b/types")]
    [System.SerializableAttribute()]
    public partial class APIPrihlasenieFilter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypObjektuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cora.CommIss.Iss.DoveraSystemClient.ArrayOfParameterAPIPrihlasenieFilterParameter ParametreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TypObjektu {
            get {
                return this.TypObjektuField;
            }
            set {
                if ((object.ReferenceEquals(this.TypObjektuField, value) != true)) {
                    this.TypObjektuField = value;
                    this.RaisePropertyChanged("TypObjektu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Cora.CommIss.Iss.DoveraSystemClient.ArrayOfParameterAPIPrihlasenieFilterParameter Parametre {
            get {
                return this.ParametreField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametreField, value) != true)) {
                    this.ParametreField = value;
                    this.RaisePropertyChanged("Parametre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfParameterAPIPrihlasenieFilterParameter", Namespace="http://schemas.dovera.sk/b2b/types", ItemName="Parameter")]
    [System.SerializableAttribute()]
    public class ArrayOfParameterAPIPrihlasenieFilterParameter : System.Collections.Generic.List<Cora.CommIss.Iss.DoveraSystemClient.APIPrihlasenieFilterParameter> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIPrihlasenieFilterParameter", Namespace="http://schemas.dovera.sk/b2b/types")]
    [System.SerializableAttribute()]
    public partial class APIPrihlasenieFilterParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string KodField;
        
        private string HodnotaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Kod {
            get {
                return this.KodField;
            }
            set {
                if ((object.ReferenceEquals(this.KodField, value) != true)) {
                    this.KodField = value;
                    this.RaisePropertyChanged("Kod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string Hodnota {
            get {
                return this.HodnotaField;
            }
            set {
                if ((object.ReferenceEquals(this.HodnotaField, value) != true)) {
                    this.HodnotaField = value;
                    this.RaisePropertyChanged("Hodnota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrihlasenieTokenomVystup", Namespace="http://b2b.dovera.sk")]
    [System.SerializableAttribute()]
    public partial class PrihlasenieTokenomVystup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlOdkazField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UrlOdkaz {
            get {
                return this.UrlOdkazField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlOdkazField, value) != true)) {
                    this.UrlOdkazField = value;
                    this.RaisePropertyChanged("UrlOdkaz");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://b2b.dovera.sk", ConfigurationName="DoveraSystemClient.SystemServiceSoap")]
    public interface SystemServiceSoap {
        
        // CODEGEN: Generating message contract since element name Vstup from namespace http://b2b.dovera.sk is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.System.DajOznamyDZP", ReplyAction="*")]
        Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPResponse DajOznamyDZP(Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.System.DajOznamyDZP", ReplyAction="*")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPResponse> DajOznamyDZPAsync(Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPRequest request);
        
        // CODEGEN: Generating message contract since element name Vstup from namespace http://b2b.dovera.sk is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.System.DajPrihlasovaciToken", ReplyAction="*")]
        Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenResponse DajPrihlasovaciToken(Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.System.DajPrihlasovaciToken", ReplyAction="*")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenResponse> DajPrihlasovaciTokenAsync(Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenRequest request);
        
        // CODEGEN: Generating message contract since element name Vstup from namespace http://b2b.dovera.sk is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.System.DajStavSystemu", ReplyAction="*")]
        Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuResponse DajStavSystemu(Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.System.DajStavSystemu", ReplyAction="*")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuResponse> DajStavSystemuAsync(Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuRequest request);
        
        // CODEGEN: Generating message contract since element name Vstup from namespace http://b2b.dovera.sk is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.System.PrihlasenieTokenom", ReplyAction="*")]
        Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomResponse PrihlasenieTokenom(Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.System.PrihlasenieTokenom", ReplyAction="*")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomResponse> PrihlasenieTokenomAsync(Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DajOznamyDZPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DajOznamyDZP", Namespace="http://b2b.dovera.sk", Order=0)]
        public Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPRequestBody Body;
        
        public DajOznamyDZPRequest() {
        }
        
        public DajOznamyDZPRequest(Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class DajOznamyDZPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPVstup Vstup;
        
        public DajOznamyDZPRequestBody() {
        }
        
        public DajOznamyDZPRequestBody(Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPVstup Vstup) {
            this.Vstup = Vstup;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DajOznamyDZPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DajOznamyDZPResponse", Namespace="http://b2b.dovera.sk", Order=0)]
        public Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPResponseBody Body;
        
        public DajOznamyDZPResponse() {
        }
        
        public DajOznamyDZPResponse(Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class DajOznamyDZPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPVystup Vystup;
        
        public DajOznamyDZPResponseBody() {
        }
        
        public DajOznamyDZPResponseBody(Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPVystup Vystup) {
            this.Vystup = Vystup;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DajPrihlasovaciTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DajPrihlasovaciToken", Namespace="http://b2b.dovera.sk", Order=0)]
        public Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenRequestBody Body;
        
        public DajPrihlasovaciTokenRequest() {
        }
        
        public DajPrihlasovaciTokenRequest(Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class DajPrihlasovaciTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenVstup Vstup;
        
        public DajPrihlasovaciTokenRequestBody() {
        }
        
        public DajPrihlasovaciTokenRequestBody(Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenVstup Vstup) {
            this.Vstup = Vstup;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DajPrihlasovaciTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DajPrihlasovaciTokenResponse", Namespace="http://b2b.dovera.sk", Order=0)]
        public Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenResponseBody Body;
        
        public DajPrihlasovaciTokenResponse() {
        }
        
        public DajPrihlasovaciTokenResponse(Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class DajPrihlasovaciTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenVystup Vystup;
        
        public DajPrihlasovaciTokenResponseBody() {
        }
        
        public DajPrihlasovaciTokenResponseBody(Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenVystup Vystup) {
            this.Vystup = Vystup;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DajStavSystemuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DajStavSystemu", Namespace="http://b2b.dovera.sk", Order=0)]
        public Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuRequestBody Body;
        
        public DajStavSystemuRequest() {
        }
        
        public DajStavSystemuRequest(Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class DajStavSystemuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuVstup Vstup;
        
        public DajStavSystemuRequestBody() {
        }
        
        public DajStavSystemuRequestBody(Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuVstup Vstup) {
            this.Vstup = Vstup;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DajStavSystemuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DajStavSystemuResponse", Namespace="http://b2b.dovera.sk", Order=0)]
        public Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuResponseBody Body;
        
        public DajStavSystemuResponse() {
        }
        
        public DajStavSystemuResponse(Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class DajStavSystemuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuVystup Vystup;
        
        public DajStavSystemuResponseBody() {
        }
        
        public DajStavSystemuResponseBody(Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuVystup Vystup) {
            this.Vystup = Vystup;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrihlasenieTokenomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrihlasenieTokenom", Namespace="http://b2b.dovera.sk", Order=0)]
        public Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomRequestBody Body;
        
        public PrihlasenieTokenomRequest() {
        }
        
        public PrihlasenieTokenomRequest(Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class PrihlasenieTokenomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomVstup Vstup;
        
        public PrihlasenieTokenomRequestBody() {
        }
        
        public PrihlasenieTokenomRequestBody(Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomVstup Vstup) {
            this.Vstup = Vstup;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrihlasenieTokenomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrihlasenieTokenomResponse", Namespace="http://b2b.dovera.sk", Order=0)]
        public Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomResponseBody Body;
        
        public PrihlasenieTokenomResponse() {
        }
        
        public PrihlasenieTokenomResponse(Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class PrihlasenieTokenomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomVystup Vystup;
        
        public PrihlasenieTokenomResponseBody() {
        }
        
        public PrihlasenieTokenomResponseBody(Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomVystup Vystup) {
            this.Vystup = Vystup;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SystemServiceSoapChannel : Cora.CommIss.Iss.DoveraSystemClient.SystemServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SystemServiceSoapClient : System.ServiceModel.ClientBase<Cora.CommIss.Iss.DoveraSystemClient.SystemServiceSoap>, Cora.CommIss.Iss.DoveraSystemClient.SystemServiceSoap {
        
        public SystemServiceSoapClient() {
        }
        
        public SystemServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPResponse Cora.CommIss.Iss.DoveraSystemClient.SystemServiceSoap.DajOznamyDZP(Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPRequest request) {
            return base.Channel.DajOznamyDZP(request);
        }
        
        public Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPVystup DajOznamyDZP(Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPVstup Vstup) {
            Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPRequest inValue = new Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPRequest();
            inValue.Body = new Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPRequestBody();
            inValue.Body.Vstup = Vstup;
            Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPResponse retVal = ((Cora.CommIss.Iss.DoveraSystemClient.SystemServiceSoap)(this)).DajOznamyDZP(inValue);
            return retVal.Body.Vystup;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPResponse> Cora.CommIss.Iss.DoveraSystemClient.SystemServiceSoap.DajOznamyDZPAsync(Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPRequest request) {
            return base.Channel.DajOznamyDZPAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPResponse> DajOznamyDZPAsync(Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPVstup Vstup) {
            Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPRequest inValue = new Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPRequest();
            inValue.Body = new Cora.CommIss.Iss.DoveraSystemClient.DajOznamyDZPRequestBody();
            inValue.Body.Vstup = Vstup;
            return ((Cora.CommIss.Iss.DoveraSystemClient.SystemServiceSoap)(this)).DajOznamyDZPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenResponse Cora.CommIss.Iss.DoveraSystemClient.SystemServiceSoap.DajPrihlasovaciToken(Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenRequest request) {
            return base.Channel.DajPrihlasovaciToken(request);
        }
        
        public Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenVystup DajPrihlasovaciToken(Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenVstup Vstup) {
            Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenRequest inValue = new Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenRequest();
            inValue.Body = new Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenRequestBody();
            inValue.Body.Vstup = Vstup;
            Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenResponse retVal = ((Cora.CommIss.Iss.DoveraSystemClient.SystemServiceSoap)(this)).DajPrihlasovaciToken(inValue);
            return retVal.Body.Vystup;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenResponse> Cora.CommIss.Iss.DoveraSystemClient.SystemServiceSoap.DajPrihlasovaciTokenAsync(Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenRequest request) {
            return base.Channel.DajPrihlasovaciTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenResponse> DajPrihlasovaciTokenAsync(Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenVstup Vstup) {
            Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenRequest inValue = new Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenRequest();
            inValue.Body = new Cora.CommIss.Iss.DoveraSystemClient.DajPrihlasovaciTokenRequestBody();
            inValue.Body.Vstup = Vstup;
            return ((Cora.CommIss.Iss.DoveraSystemClient.SystemServiceSoap)(this)).DajPrihlasovaciTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuResponse Cora.CommIss.Iss.DoveraSystemClient.SystemServiceSoap.DajStavSystemu(Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuRequest request) {
            return base.Channel.DajStavSystemu(request);
        }
        
        public Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuVystup DajStavSystemu(Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuVstup Vstup) {
            Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuRequest inValue = new Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuRequest();
            inValue.Body = new Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuRequestBody();
            inValue.Body.Vstup = Vstup;
            Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuResponse retVal = ((Cora.CommIss.Iss.DoveraSystemClient.SystemServiceSoap)(this)).DajStavSystemu(inValue);
            return retVal.Body.Vystup;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuResponse> Cora.CommIss.Iss.DoveraSystemClient.SystemServiceSoap.DajStavSystemuAsync(Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuRequest request) {
            return base.Channel.DajStavSystemuAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuResponse> DajStavSystemuAsync(Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuVstup Vstup) {
            Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuRequest inValue = new Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuRequest();
            inValue.Body = new Cora.CommIss.Iss.DoveraSystemClient.DajStavSystemuRequestBody();
            inValue.Body.Vstup = Vstup;
            return ((Cora.CommIss.Iss.DoveraSystemClient.SystemServiceSoap)(this)).DajStavSystemuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomResponse Cora.CommIss.Iss.DoveraSystemClient.SystemServiceSoap.PrihlasenieTokenom(Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomRequest request) {
            return base.Channel.PrihlasenieTokenom(request);
        }
        
        public Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomVystup PrihlasenieTokenom(Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomVstup Vstup) {
            Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomRequest inValue = new Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomRequest();
            inValue.Body = new Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomRequestBody();
            inValue.Body.Vstup = Vstup;
            Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomResponse retVal = ((Cora.CommIss.Iss.DoveraSystemClient.SystemServiceSoap)(this)).PrihlasenieTokenom(inValue);
            return retVal.Body.Vystup;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomResponse> Cora.CommIss.Iss.DoveraSystemClient.SystemServiceSoap.PrihlasenieTokenomAsync(Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomRequest request) {
            return base.Channel.PrihlasenieTokenomAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomResponse> PrihlasenieTokenomAsync(Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomVstup Vstup) {
            Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomRequest inValue = new Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomRequest();
            inValue.Body = new Cora.CommIss.Iss.DoveraSystemClient.PrihlasenieTokenomRequestBody();
            inValue.Body.Vstup = Vstup;
            return ((Cora.CommIss.Iss.DoveraSystemClient.SystemServiceSoap)(this)).PrihlasenieTokenomAsync(inValue);
        }
    }
}
