//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cora.CommIss.Iss.DoveraPlatitelClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://b2b.dovera.sk", ConfigurationName="DoveraPlatitelClient.PlatitelSoapServiceSoap")]
    public interface PlatitelSoapServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.HPP.Platitel.AktualizujUdajeZamestnav" +
            "atela", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Vystup")]
        Cora.CommIss.Iss.DoveraPlatitelClient.AktualizujUdajeZamestnavatelaVystup AktualizujUdajeZamestnavatela(Cora.CommIss.Iss.DoveraPlatitelClient.AktualizujUdajeZamestnavatelaVstup Vstup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.HPP.Platitel.AktualizujUdajeZamestnav" +
            "atela", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Vystup")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraPlatitelClient.AktualizujUdajeZamestnavatelaVystup> AktualizujUdajeZamestnavatelaAsync(Cora.CommIss.Iss.DoveraPlatitelClient.AktualizujUdajeZamestnavatelaVstup Vstup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.HPP.Platitel.DajStavUctu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Vystup")]
        Cora.CommIss.Iss.DoveraPlatitelClient.DajStavUctuVystup DajStavUctu(Cora.CommIss.Iss.DoveraPlatitelClient.DajStavUctuVstup Vstup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.HPP.Platitel.DajStavUctu", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Vystup")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraPlatitelClient.DajStavUctuVystup> DajStavUctuAsync(Cora.CommIss.Iss.DoveraPlatitelClient.DajStavUctuVstup Vstup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.HPP.Platitel.DajUdajeZamestnavatela", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Vystup")]
        Cora.CommIss.Iss.DoveraPlatitelClient.DajUdajeZamestnavatelaVystup DajUdajeZamestnavatela(Cora.CommIss.Iss.DoveraPlatitelClient.DajUdajeZamestnavatelaVstup Vstup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.HPP.Platitel.DajUdajeZamestnavatela", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Vystup")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraPlatitelClient.DajUdajeZamestnavatelaVystup> DajUdajeZamestnavatelaAsync(Cora.CommIss.Iss.DoveraPlatitelClient.DajUdajeZamestnavatelaVstup Vstup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.HPP.Platitel.DajVysledokOvereniaZnize" +
            "naSadzba", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Vystup")]
        Cora.CommIss.Iss.DoveraPlatitelClient.DajVysledokOvereniaZnizenaSadzbaVystup DajVysledokOvereniaZnizenaSadzba(Cora.CommIss.Iss.DoveraPlatitelClient.DajVysledokOvereniaZnizenaSadzbaVstup Vstup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.HPP.Platitel.DajVysledokOvereniaZnize" +
            "naSadzba", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Vystup")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraPlatitelClient.DajVysledokOvereniaZnizenaSadzbaVystup> DajVysledokOvereniaZnizenaSadzbaAsync(Cora.CommIss.Iss.DoveraPlatitelClient.DajVysledokOvereniaZnizenaSadzbaVstup Vstup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.HPP.Platitel.DajZoznamZamestnancov", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Vystup")]
        Cora.CommIss.Iss.DoveraPlatitelClient.DajZoznamZamestnancovVystup DajZoznamZamestnancov(Cora.CommIss.Iss.DoveraPlatitelClient.DajZoznamZamestnancovVstup Vstup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.HPP.Platitel.DajZoznamZamestnancov", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Vystup")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraPlatitelClient.DajZoznamZamestnancovVystup> DajZoznamZamestnancovAsync(Cora.CommIss.Iss.DoveraPlatitelClient.DajZoznamZamestnancovVstup Vstup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.HPP.Platitel.OverNarokNaZnizenuSadzbu" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Vystup")]
        Cora.CommIss.Iss.DoveraPlatitelClient.OverNarokNaZnizenuSadzbuVystup OverNarokNaZnizenuSadzbu(Cora.CommIss.Iss.DoveraPlatitelClient.OverNarokNaZnizenuSadzbuVstup Vstup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.HPP.Platitel.OverNarokNaZnizenuSadzbu" +
            "", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Vystup")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraPlatitelClient.OverNarokNaZnizenuSadzbuVystup> OverNarokNaZnizenuSadzbuAsync(Cora.CommIss.Iss.DoveraPlatitelClient.OverNarokNaZnizenuSadzbuVstup Vstup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.HPP.Platitel.OverOOP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Vystup")]
        Cora.CommIss.Iss.DoveraPlatitelClient.OverOOPVystup OverOOP(Cora.CommIss.Iss.DoveraPlatitelClient.OverOOPVstup Vstup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.HPP.Platitel.OverOOP", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Vystup")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraPlatitelClient.OverOOPVystup> OverOOPAsync(Cora.CommIss.Iss.DoveraPlatitelClient.OverOOPVstup Vstup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.HPP.Platitel.OverPlatitela", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Vystup")]
        Cora.CommIss.Iss.DoveraPlatitelClient.OverPlatitelaVystup OverPlatitela(Cora.CommIss.Iss.DoveraPlatitelClient.OverPlatitelaVstup Vstup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.dovera.sk/ESB.Service.WS.B2B.V02.HPP.Platitel.OverPlatitela", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Vystup")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraPlatitelClient.OverPlatitelaVystup> OverPlatitelaAsync(Cora.CommIss.Iss.DoveraPlatitelClient.OverPlatitelaVstup Vstup);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class AktualizujUdajeZamestnavatelaVstup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private APITokenPouzivatela tokenPouzivatelaField;
        
        private APIRegistracneUdaje registracneUdajeField;
        
        private string kodZmenyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public APITokenPouzivatela TokenPouzivatela {
            get {
                return this.tokenPouzivatelaField;
            }
            set {
                this.tokenPouzivatelaField = value;
                this.RaisePropertyChanged("TokenPouzivatela");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public APIRegistracneUdaje RegistracneUdaje {
            get {
                return this.registracneUdajeField;
            }
            set {
                this.registracneUdajeField = value;
                this.RaisePropertyChanged("RegistracneUdaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string KodZmeny {
            get {
                return this.kodZmenyField;
            }
            set {
                this.kodZmenyField = value;
                this.RaisePropertyChanged("KodZmeny");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dovera.sk/b2b/types")]
    public partial class APITokenPouzivatela : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string dodavatelSWField;
        
        private string kodNZField;
        
        private string kodVZField;
        
        private string vsField;
        
        private string unikatnyKodPLAField;
        
        private int casovyLimitVolaniaField;
        
        private bool casovyLimitVolaniaFieldSpecified;
        
        private string iCOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("Login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DodavatelSW {
            get {
                return this.dodavatelSWField;
            }
            set {
                this.dodavatelSWField = value;
                this.RaisePropertyChanged("DodavatelSW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string KodNZ {
            get {
                return this.kodNZField;
            }
            set {
                this.kodNZField = value;
                this.RaisePropertyChanged("KodNZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string KodVZ {
            get {
                return this.kodVZField;
            }
            set {
                this.kodVZField = value;
                this.RaisePropertyChanged("KodVZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string VS {
            get {
                return this.vsField;
            }
            set {
                this.vsField = value;
                this.RaisePropertyChanged("VS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string UnikatnyKodPLA {
            get {
                return this.unikatnyKodPLAField;
            }
            set {
                this.unikatnyKodPLAField = value;
                this.RaisePropertyChanged("UnikatnyKodPLA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int CasovyLimitVolania {
            get {
                return this.casovyLimitVolaniaField;
            }
            set {
                this.casovyLimitVolaniaField = value;
                this.RaisePropertyChanged("CasovyLimitVolania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CasovyLimitVolaniaSpecified {
            get {
                return this.casovyLimitVolaniaFieldSpecified;
            }
            set {
                this.casovyLimitVolaniaFieldSpecified = value;
                this.RaisePropertyChanged("CasovyLimitVolaniaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ICO {
            get {
                return this.iCOField;
            }
            set {
                this.iCOField = value;
                this.RaisePropertyChanged("ICO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class OverPlatitelaVystup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iCORCField;
        
        private System.DateTime datumCasOvereniaField;
        
        private OverPlatitelaVystupStavPlatitela stavPlatitelaField;
        
        private bool maSPKField;
        
        private decimal sumaDlznaField;
        
        private bool sumaDlznaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ICORC {
            get {
                return this.iCORCField;
            }
            set {
                this.iCORCField = value;
                this.RaisePropertyChanged("ICORC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime DatumCasOverenia {
            get {
                return this.datumCasOvereniaField;
            }
            set {
                this.datumCasOvereniaField = value;
                this.RaisePropertyChanged("DatumCasOverenia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public OverPlatitelaVystupStavPlatitela StavPlatitela {
            get {
                return this.stavPlatitelaField;
            }
            set {
                this.stavPlatitelaField = value;
                this.RaisePropertyChanged("StavPlatitela");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool MaSPK {
            get {
                return this.maSPKField;
            }
            set {
                this.maSPKField = value;
                this.RaisePropertyChanged("MaSPK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal SumaDlzna {
            get {
                return this.sumaDlznaField;
            }
            set {
                this.sumaDlznaField = value;
                this.RaisePropertyChanged("SumaDlzna");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SumaDlznaSpecified {
            get {
                return this.sumaDlznaFieldSpecified;
            }
            set {
                this.sumaDlznaFieldSpecified = value;
                this.RaisePropertyChanged("SumaDlznaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://b2b.dovera.sk")]
    public enum OverPlatitelaVystupStavPlatitela {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        RN,
        
        /// <remarks/>
        RD,
        
        /// <remarks/>
        PN,
        
        /// <remarks/>
        PD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class OverPlatitelaVstup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private APITokenPouzivatela tokenPouzivatelaField;
        
        private string iCORCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public APITokenPouzivatela TokenPouzivatela {
            get {
                return this.tokenPouzivatelaField;
            }
            set {
                this.tokenPouzivatelaField = value;
                this.RaisePropertyChanged("TokenPouzivatela");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ICORC {
            get {
                return this.iCORCField;
            }
            set {
                this.iCORCField = value;
                this.RaisePropertyChanged("ICORC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dovera.sk/b2b/types")]
    public partial class APINarokNaOOP : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime datumOdField;
        
        private System.DateTime datumDoField;
        
        private string vysledokField;
        
        private string[] dovodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DatumOd {
            get {
                return this.datumOdField;
            }
            set {
                this.datumOdField = value;
                this.RaisePropertyChanged("DatumOd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime DatumDo {
            get {
                return this.datumDoField;
            }
            set {
                this.datumDoField = value;
                this.RaisePropertyChanged("DatumDo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Vysledok {
            get {
                return this.vysledokField;
            }
            set {
                this.vysledokField = value;
                this.RaisePropertyChanged("Vysledok");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Dovod")]
        public string[] Dovody {
            get {
                return this.dovodyField;
            }
            set {
                this.dovodyField = value;
                this.RaisePropertyChanged("Dovody");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class OverOOPVystup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vsField;
        
        private string rcField;
        
        private System.DateTime rozhodnyDenField;
        
        private System.DateTime datumCasOvereniaField;
        
        private APINarokNaOOP narokNaOOPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string VS {
            get {
                return this.vsField;
            }
            set {
                this.vsField = value;
                this.RaisePropertyChanged("VS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RC {
            get {
                return this.rcField;
            }
            set {
                this.rcField = value;
                this.RaisePropertyChanged("RC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime RozhodnyDen {
            get {
                return this.rozhodnyDenField;
            }
            set {
                this.rozhodnyDenField = value;
                this.RaisePropertyChanged("RozhodnyDen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime DatumCasOverenia {
            get {
                return this.datumCasOvereniaField;
            }
            set {
                this.datumCasOvereniaField = value;
                this.RaisePropertyChanged("DatumCasOverenia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public APINarokNaOOP NarokNaOOP {
            get {
                return this.narokNaOOPField;
            }
            set {
                this.narokNaOOPField = value;
                this.RaisePropertyChanged("NarokNaOOP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class OverOOPVstup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private APITokenPouzivatela tokenPouzivatelaField;
        
        private string rcField;
        
        private string iCPField;
        
        private System.DateTime rozhodnyDenField;
        
        private bool rozhodnyDenFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public APITokenPouzivatela TokenPouzivatela {
            get {
                return this.tokenPouzivatelaField;
            }
            set {
                this.tokenPouzivatelaField = value;
                this.RaisePropertyChanged("TokenPouzivatela");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RC {
            get {
                return this.rcField;
            }
            set {
                this.rcField = value;
                this.RaisePropertyChanged("RC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ICP {
            get {
                return this.iCPField;
            }
            set {
                this.iCPField = value;
                this.RaisePropertyChanged("ICP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime RozhodnyDen {
            get {
                return this.rozhodnyDenField;
            }
            set {
                this.rozhodnyDenField = value;
                this.RaisePropertyChanged("RozhodnyDen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RozhodnyDenSpecified {
            get {
                return this.rozhodnyDenFieldSpecified;
            }
            set {
                this.rozhodnyDenFieldSpecified = value;
                this.RaisePropertyChanged("RozhodnyDenSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class OverNarokNaZnizenuSadzbuVystup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private APIVysledokOverenia vysledokField;
        
        private long idVolaniaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public APIVysledokOverenia Vysledok {
            get {
                return this.vysledokField;
            }
            set {
                this.vysledokField = value;
                this.RaisePropertyChanged("Vysledok");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long IdVolania {
            get {
                return this.idVolaniaField;
            }
            set {
                this.idVolaniaField = value;
                this.RaisePropertyChanged("IdVolania");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dovera.sk/b2b/types")]
    public partial class APIVysledokOverenia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string stavField;
        
        private APIVysledokZnizenaSadzba[] vysledokZnizeneSadzbyField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Stav {
            get {
                return this.stavField;
            }
            set {
                this.stavField = value;
                this.RaisePropertyChanged("Stav");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("VysledokZnizenaSadzba")]
        public APIVysledokZnizenaSadzba[] VysledokZnizeneSadzby {
            get {
                return this.vysledokZnizeneSadzbyField;
            }
            set {
                this.vysledokZnizeneSadzbyField = value;
                this.RaisePropertyChanged("VysledokZnizeneSadzby");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dovera.sk/b2b/types")]
    public partial class APIVysledokZnizenaSadzba : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int obdobieField;
        
        private string rodneCisloField;
        
        private System.DateTime datumCasOvereniaField;
        
        private string vysledokField;
        
        private string logField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Obdobie {
            get {
                return this.obdobieField;
            }
            set {
                this.obdobieField = value;
                this.RaisePropertyChanged("Obdobie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RodneCislo {
            get {
                return this.rodneCisloField;
            }
            set {
                this.rodneCisloField = value;
                this.RaisePropertyChanged("RodneCislo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime DatumCasOverenia {
            get {
                return this.datumCasOvereniaField;
            }
            set {
                this.datumCasOvereniaField = value;
                this.RaisePropertyChanged("DatumCasOverenia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Vysledok {
            get {
                return this.vysledokField;
            }
            set {
                this.vysledokField = value;
                this.RaisePropertyChanged("Vysledok");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Log {
            get {
                return this.logField;
            }
            set {
                this.logField = value;
                this.RaisePropertyChanged("Log");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class OverNarokNaZnizenuSadzbuVstup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private APITokenPouzivatela tokenPouzivatelaField;
        
        private string[] rodneCislaField;
        
        private int obdobieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public APITokenPouzivatela TokenPouzivatela {
            get {
                return this.tokenPouzivatelaField;
            }
            set {
                this.tokenPouzivatelaField = value;
                this.RaisePropertyChanged("TokenPouzivatela");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RodneCislo")]
        public string[] RodneCisla {
            get {
                return this.rodneCislaField;
            }
            set {
                this.rodneCislaField = value;
                this.RaisePropertyChanged("RodneCisla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Obdobie {
            get {
                return this.obdobieField;
            }
            set {
                this.obdobieField = value;
                this.RaisePropertyChanged("Obdobie");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dovera.sk/b2b/types")]
    public partial class APIKategoria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime datumOdField;
        
        private System.DateTime datumDoField;
        
        private bool datumDoFieldSpecified;
        
        private string typField;
        
        private string podtypField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DatumOd {
            get {
                return this.datumOdField;
            }
            set {
                this.datumOdField = value;
                this.RaisePropertyChanged("DatumOd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime DatumDo {
            get {
                return this.datumDoField;
            }
            set {
                this.datumDoField = value;
                this.RaisePropertyChanged("DatumDo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatumDoSpecified {
            get {
                return this.datumDoFieldSpecified;
            }
            set {
                this.datumDoFieldSpecified = value;
                this.RaisePropertyChanged("DatumDoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Typ {
            get {
                return this.typField;
            }
            set {
                this.typField = value;
                this.RaisePropertyChanged("Typ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Podtyp {
            get {
                return this.podtypField;
            }
            set {
                this.podtypField = value;
                this.RaisePropertyChanged("Podtyp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dovera.sk/b2b/types")]
    public partial class APIPoisteniePoistenca : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime datumOdField;
        
        private bool datumOdFieldSpecified;
        
        private System.DateTime datumDoField;
        
        private bool datumDoFieldSpecified;
        
        private APIKategoria[] kategorieField;
        
        private APIPoistnyVztahPoistenca stavPoisteniaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DatumOd {
            get {
                return this.datumOdField;
            }
            set {
                this.datumOdField = value;
                this.RaisePropertyChanged("DatumOd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatumOdSpecified {
            get {
                return this.datumOdFieldSpecified;
            }
            set {
                this.datumOdFieldSpecified = value;
                this.RaisePropertyChanged("DatumOdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime DatumDo {
            get {
                return this.datumDoField;
            }
            set {
                this.datumDoField = value;
                this.RaisePropertyChanged("DatumDo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatumDoSpecified {
            get {
                return this.datumDoFieldSpecified;
            }
            set {
                this.datumDoFieldSpecified = value;
                this.RaisePropertyChanged("DatumDoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Kategoria")]
        public APIKategoria[] Kategorie {
            get {
                return this.kategorieField;
            }
            set {
                this.kategorieField = value;
                this.RaisePropertyChanged("Kategorie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public APIPoistnyVztahPoistenca StavPoistenia {
            get {
                return this.stavPoisteniaField;
            }
            set {
                this.stavPoisteniaField = value;
                this.RaisePropertyChanged("StavPoistenia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dovera.sk/b2b/types")]
    public enum APIPoistnyVztahPoistenca {
        
        /// <remarks/>
        NieJePoistencom,
        
        /// <remarks/>
        JePoistencom,
        
        /// <remarks/>
        JePoistencomEU,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dovera.sk/b2b/types")]
    public partial class APIZamestnanec : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rcField;
        
        private string menoField;
        
        private string priezviskoField;
        
        private bool jeNeplaticField;
        
        private bool jeNeplaticFieldSpecified;
        
        private APIPoisteniePoistenca[] poisteniaPoistencaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RC {
            get {
                return this.rcField;
            }
            set {
                this.rcField = value;
                this.RaisePropertyChanged("RC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Meno {
            get {
                return this.menoField;
            }
            set {
                this.menoField = value;
                this.RaisePropertyChanged("Meno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Priezvisko {
            get {
                return this.priezviskoField;
            }
            set {
                this.priezviskoField = value;
                this.RaisePropertyChanged("Priezvisko");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool JeNeplatic {
            get {
                return this.jeNeplaticField;
            }
            set {
                this.jeNeplaticField = value;
                this.RaisePropertyChanged("JeNeplatic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JeNeplaticSpecified {
            get {
                return this.jeNeplaticFieldSpecified;
            }
            set {
                this.jeNeplaticFieldSpecified = value;
                this.RaisePropertyChanged("JeNeplaticSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PoisteniePoistenca")]
        public APIPoisteniePoistenca[] PoisteniaPoistenca {
            get {
                return this.poisteniaPoistencaField;
            }
            set {
                this.poisteniaPoistencaField = value;
                this.RaisePropertyChanged("PoisteniaPoistenca");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class DajZoznamZamestnancovVystup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private APIZamestnanec[] zoznamZamestnancovField;
        
        private long idKategorieOdField;
        
        private bool idKategorieOdFieldSpecified;
        
        private bool existujeDalsiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Zamestnanec")]
        public APIZamestnanec[] ZoznamZamestnancov {
            get {
                return this.zoznamZamestnancovField;
            }
            set {
                this.zoznamZamestnancovField = value;
                this.RaisePropertyChanged("ZoznamZamestnancov");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long IdKategorieOd {
            get {
                return this.idKategorieOdField;
            }
            set {
                this.idKategorieOdField = value;
                this.RaisePropertyChanged("IdKategorieOd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdKategorieOdSpecified {
            get {
                return this.idKategorieOdFieldSpecified;
            }
            set {
                this.idKategorieOdFieldSpecified = value;
                this.RaisePropertyChanged("IdKategorieOdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool ExistujeDalsi {
            get {
                return this.existujeDalsiField;
            }
            set {
                this.existujeDalsiField = value;
                this.RaisePropertyChanged("ExistujeDalsi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class DajZoznamZamestnancovVstup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private APITokenPouzivatela tokenPouzivatelaField;
        
        private System.DateTime datumOdField;
        
        private System.DateTime datumDoField;
        
        private bool datumDoFieldSpecified;
        
        private long idKategorieOdField;
        
        private bool idKategorieOdFieldSpecified;
        
        private string[] rodneCislaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public APITokenPouzivatela TokenPouzivatela {
            get {
                return this.tokenPouzivatelaField;
            }
            set {
                this.tokenPouzivatelaField = value;
                this.RaisePropertyChanged("TokenPouzivatela");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime DatumOd {
            get {
                return this.datumOdField;
            }
            set {
                this.datumOdField = value;
                this.RaisePropertyChanged("DatumOd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime DatumDo {
            get {
                return this.datumDoField;
            }
            set {
                this.datumDoField = value;
                this.RaisePropertyChanged("DatumDo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatumDoSpecified {
            get {
                return this.datumDoFieldSpecified;
            }
            set {
                this.datumDoFieldSpecified = value;
                this.RaisePropertyChanged("DatumDoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long IdKategorieOd {
            get {
                return this.idKategorieOdField;
            }
            set {
                this.idKategorieOdField = value;
                this.RaisePropertyChanged("IdKategorieOd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdKategorieOdSpecified {
            get {
                return this.idKategorieOdFieldSpecified;
            }
            set {
                this.idKategorieOdFieldSpecified = value;
                this.RaisePropertyChanged("IdKategorieOdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RodneCisla", IsNullable=true, Order=4)]
        public string[] RodneCisla {
            get {
                return this.rodneCislaField;
            }
            set {
                this.rodneCislaField = value;
                this.RaisePropertyChanged("RodneCisla");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class DajVysledokOvereniaZnizenaSadzbaVystup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private APIVysledokOverenia vysledokField;
        
        private long idVolaniaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public APIVysledokOverenia Vysledok {
            get {
                return this.vysledokField;
            }
            set {
                this.vysledokField = value;
                this.RaisePropertyChanged("Vysledok");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long IdVolania {
            get {
                return this.idVolaniaField;
            }
            set {
                this.idVolaniaField = value;
                this.RaisePropertyChanged("IdVolania");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class DajVysledokOvereniaZnizenaSadzbaVstup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private APITokenPouzivatela tokenPouzivatelaField;
        
        private long idVolaniaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public APITokenPouzivatela TokenPouzivatela {
            get {
                return this.tokenPouzivatelaField;
            }
            set {
                this.tokenPouzivatelaField = value;
                this.RaisePropertyChanged("TokenPouzivatela");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long IdVolania {
            get {
                return this.idVolaniaField;
            }
            set {
                this.idVolaniaField = value;
                this.RaisePropertyChanged("IdVolania");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dovera.sk/b2b/types")]
    public partial class APIUdajeZamestnavatela : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vsField;
        
        private APIRegistracneUdaje registracneUdajeField;
        
        private string ssField;
        
        private string unikatnyKodPlaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string VS {
            get {
                return this.vsField;
            }
            set {
                this.vsField = value;
                this.RaisePropertyChanged("VS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public APIRegistracneUdaje RegistracneUdaje {
            get {
                return this.registracneUdajeField;
            }
            set {
                this.registracneUdajeField = value;
                this.RaisePropertyChanged("RegistracneUdaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SS {
            get {
                return this.ssField;
            }
            set {
                this.ssField = value;
                this.RaisePropertyChanged("SS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UnikatnyKodPla {
            get {
                return this.unikatnyKodPlaField;
            }
            set {
                this.unikatnyKodPlaField = value;
                this.RaisePropertyChanged("UnikatnyKodPla");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dovera.sk/b2b/types")]
    public partial class APIRegistracneUdaje : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nazovField;
        
        private string nazovOJField;
        
        private APIAdresa[] adresyField;
        
        private APIBankovyUcet[] bankoveUctyField;
        
        private int vyplatnyTerminField;
        
        private bool vyplatnyTerminFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nazov {
            get {
                return this.nazovField;
            }
            set {
                this.nazovField = value;
                this.RaisePropertyChanged("Nazov");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NazovOJ {
            get {
                return this.nazovOJField;
            }
            set {
                this.nazovOJField = value;
                this.RaisePropertyChanged("NazovOJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Adresa")]
        public APIAdresa[] Adresy {
            get {
                return this.adresyField;
            }
            set {
                this.adresyField = value;
                this.RaisePropertyChanged("Adresy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("BankovyUcet")]
        public APIBankovyUcet[] BankoveUcty {
            get {
                return this.bankoveUctyField;
            }
            set {
                this.bankoveUctyField = value;
                this.RaisePropertyChanged("BankoveUcty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int VyplatnyTermin {
            get {
                return this.vyplatnyTerminField;
            }
            set {
                this.vyplatnyTerminField = value;
                this.RaisePropertyChanged("VyplatnyTermin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VyplatnyTerminSpecified {
            get {
                return this.vyplatnyTerminFieldSpecified;
            }
            set {
                this.vyplatnyTerminFieldSpecified = value;
                this.RaisePropertyChanged("VyplatnyTerminSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dovera.sk/b2b/types")]
    public partial class APIAdresa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string typField;
        
        private string obecField;
        
        private string ulicaField;
        
        private string popisneCisloField;
        
        private string pSCField;
        
        private string statField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Typ {
            get {
                return this.typField;
            }
            set {
                this.typField = value;
                this.RaisePropertyChanged("Typ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Obec {
            get {
                return this.obecField;
            }
            set {
                this.obecField = value;
                this.RaisePropertyChanged("Obec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Ulica {
            get {
                return this.ulicaField;
            }
            set {
                this.ulicaField = value;
                this.RaisePropertyChanged("Ulica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PopisneCislo {
            get {
                return this.popisneCisloField;
            }
            set {
                this.popisneCisloField = value;
                this.RaisePropertyChanged("PopisneCislo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PSC {
            get {
                return this.pSCField;
            }
            set {
                this.pSCField = value;
                this.RaisePropertyChanged("PSC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Stat {
            get {
                return this.statField;
            }
            set {
                this.statField = value;
                this.RaisePropertyChanged("Stat");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dovera.sk/b2b/types")]
    public partial class APIBankovyUcet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string iBANField;
        
        private System.DateTime platnostOdField;
        
        private System.DateTime platnostDoField;
        
        private bool platnostDoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
                this.RaisePropertyChanged("IBAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime PlatnostOd {
            get {
                return this.platnostOdField;
            }
            set {
                this.platnostOdField = value;
                this.RaisePropertyChanged("PlatnostOd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime PlatnostDo {
            get {
                return this.platnostDoField;
            }
            set {
                this.platnostDoField = value;
                this.RaisePropertyChanged("PlatnostDo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlatnostDoSpecified {
            get {
                return this.platnostDoFieldSpecified;
            }
            set {
                this.platnostDoFieldSpecified = value;
                this.RaisePropertyChanged("PlatnostDoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class DajUdajeZamestnavatelaVystup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private APIUdajeZamestnavatela[] udajeZamestnavatelovField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("UdajeZamestnavatela")]
        public APIUdajeZamestnavatela[] UdajeZamestnavatelov {
            get {
                return this.udajeZamestnavatelovField;
            }
            set {
                this.udajeZamestnavatelovField = value;
                this.RaisePropertyChanged("UdajeZamestnavatelov");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class DajUdajeZamestnavatelaVstup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private APITokenPouzivatela tokenPouzivatelaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public APITokenPouzivatela TokenPouzivatela {
            get {
                return this.tokenPouzivatelaField;
            }
            set {
                this.tokenPouzivatelaField = value;
                this.RaisePropertyChanged("TokenPouzivatela");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class DajStavUctuVystup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vsField;
        
        private System.DateTime datumCasOvereniaField;
        
        private decimal dlhPoSplatnostiField;
        
        private decimal dlhCelkomField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string VS {
            get {
                return this.vsField;
            }
            set {
                this.vsField = value;
                this.RaisePropertyChanged("VS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime DatumCasOverenia {
            get {
                return this.datumCasOvereniaField;
            }
            set {
                this.datumCasOvereniaField = value;
                this.RaisePropertyChanged("DatumCasOverenia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal DlhPoSplatnosti {
            get {
                return this.dlhPoSplatnostiField;
            }
            set {
                this.dlhPoSplatnostiField = value;
                this.RaisePropertyChanged("DlhPoSplatnosti");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal DlhCelkom {
            get {
                return this.dlhCelkomField;
            }
            set {
                this.dlhCelkomField = value;
                this.RaisePropertyChanged("DlhCelkom");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class DajStavUctuVstup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private APITokenPouzivatela tokenPouzivatelaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public APITokenPouzivatela TokenPouzivatela {
            get {
                return this.tokenPouzivatelaField;
            }
            set {
                this.tokenPouzivatelaField = value;
                this.RaisePropertyChanged("TokenPouzivatela");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.dovera.sk")]
    public partial class AktualizujUdajeZamestnavatelaVystup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool vysledokField;
        
        private string chybyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Vysledok {
            get {
                return this.vysledokField;
            }
            set {
                this.vysledokField = value;
                this.RaisePropertyChanged("Vysledok");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Chyby {
            get {
                return this.chybyField;
            }
            set {
                this.chybyField = value;
                this.RaisePropertyChanged("Chyby");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlatitelSoapServiceSoapChannel : Cora.CommIss.Iss.DoveraPlatitelClient.PlatitelSoapServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlatitelSoapServiceSoapClient : System.ServiceModel.ClientBase<Cora.CommIss.Iss.DoveraPlatitelClient.PlatitelSoapServiceSoap>, Cora.CommIss.Iss.DoveraPlatitelClient.PlatitelSoapServiceSoap {
        
        public PlatitelSoapServiceSoapClient() {
        }
        
        public PlatitelSoapServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlatitelSoapServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlatitelSoapServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlatitelSoapServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cora.CommIss.Iss.DoveraPlatitelClient.AktualizujUdajeZamestnavatelaVystup AktualizujUdajeZamestnavatela(Cora.CommIss.Iss.DoveraPlatitelClient.AktualizujUdajeZamestnavatelaVstup Vstup) {
            return base.Channel.AktualizujUdajeZamestnavatela(Vstup);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraPlatitelClient.AktualizujUdajeZamestnavatelaVystup> AktualizujUdajeZamestnavatelaAsync(Cora.CommIss.Iss.DoveraPlatitelClient.AktualizujUdajeZamestnavatelaVstup Vstup) {
            return base.Channel.AktualizujUdajeZamestnavatelaAsync(Vstup);
        }
        
        public Cora.CommIss.Iss.DoveraPlatitelClient.DajStavUctuVystup DajStavUctu(Cora.CommIss.Iss.DoveraPlatitelClient.DajStavUctuVstup Vstup) {
            return base.Channel.DajStavUctu(Vstup);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraPlatitelClient.DajStavUctuVystup> DajStavUctuAsync(Cora.CommIss.Iss.DoveraPlatitelClient.DajStavUctuVstup Vstup) {
            return base.Channel.DajStavUctuAsync(Vstup);
        }
        
        public Cora.CommIss.Iss.DoveraPlatitelClient.DajUdajeZamestnavatelaVystup DajUdajeZamestnavatela(Cora.CommIss.Iss.DoveraPlatitelClient.DajUdajeZamestnavatelaVstup Vstup) {
            return base.Channel.DajUdajeZamestnavatela(Vstup);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraPlatitelClient.DajUdajeZamestnavatelaVystup> DajUdajeZamestnavatelaAsync(Cora.CommIss.Iss.DoveraPlatitelClient.DajUdajeZamestnavatelaVstup Vstup) {
            return base.Channel.DajUdajeZamestnavatelaAsync(Vstup);
        }
        
        public Cora.CommIss.Iss.DoveraPlatitelClient.DajVysledokOvereniaZnizenaSadzbaVystup DajVysledokOvereniaZnizenaSadzba(Cora.CommIss.Iss.DoveraPlatitelClient.DajVysledokOvereniaZnizenaSadzbaVstup Vstup) {
            return base.Channel.DajVysledokOvereniaZnizenaSadzba(Vstup);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraPlatitelClient.DajVysledokOvereniaZnizenaSadzbaVystup> DajVysledokOvereniaZnizenaSadzbaAsync(Cora.CommIss.Iss.DoveraPlatitelClient.DajVysledokOvereniaZnizenaSadzbaVstup Vstup) {
            return base.Channel.DajVysledokOvereniaZnizenaSadzbaAsync(Vstup);
        }
        
        public Cora.CommIss.Iss.DoveraPlatitelClient.DajZoznamZamestnancovVystup DajZoznamZamestnancov(Cora.CommIss.Iss.DoveraPlatitelClient.DajZoznamZamestnancovVstup Vstup) {
            return base.Channel.DajZoznamZamestnancov(Vstup);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraPlatitelClient.DajZoznamZamestnancovVystup> DajZoznamZamestnancovAsync(Cora.CommIss.Iss.DoveraPlatitelClient.DajZoznamZamestnancovVstup Vstup) {
            return base.Channel.DajZoznamZamestnancovAsync(Vstup);
        }
        
        public Cora.CommIss.Iss.DoveraPlatitelClient.OverNarokNaZnizenuSadzbuVystup OverNarokNaZnizenuSadzbu(Cora.CommIss.Iss.DoveraPlatitelClient.OverNarokNaZnizenuSadzbuVstup Vstup) {
            return base.Channel.OverNarokNaZnizenuSadzbu(Vstup);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraPlatitelClient.OverNarokNaZnizenuSadzbuVystup> OverNarokNaZnizenuSadzbuAsync(Cora.CommIss.Iss.DoveraPlatitelClient.OverNarokNaZnizenuSadzbuVstup Vstup) {
            return base.Channel.OverNarokNaZnizenuSadzbuAsync(Vstup);
        }
        
        public Cora.CommIss.Iss.DoveraPlatitelClient.OverOOPVystup OverOOP(Cora.CommIss.Iss.DoveraPlatitelClient.OverOOPVstup Vstup) {
            return base.Channel.OverOOP(Vstup);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraPlatitelClient.OverOOPVystup> OverOOPAsync(Cora.CommIss.Iss.DoveraPlatitelClient.OverOOPVstup Vstup) {
            return base.Channel.OverOOPAsync(Vstup);
        }
        
        public Cora.CommIss.Iss.DoveraPlatitelClient.OverPlatitelaVystup OverPlatitela(Cora.CommIss.Iss.DoveraPlatitelClient.OverPlatitelaVstup Vstup) {
            return base.Channel.OverPlatitela(Vstup);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.DoveraPlatitelClient.OverPlatitelaVystup> OverPlatitelaAsync(Cora.CommIss.Iss.DoveraPlatitelClient.OverPlatitelaVstup Vstup) {
            return base.Channel.OverPlatitelaAsync(Vstup);
        }
    }
}
