//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recipient", Namespace="http://www.corageo.sk/schemas/CommIss")]
    [System.SerializableAttribute()]
    public partial class Recipient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sender", Namespace="http://www.corageo.sk/schemas/CommIss")]
    [System.SerializableAttribute()]
    public partial class Sender : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZelenaPostaResponse", Namespace="http://www.corageo.sk/schemas/CommIss")]
    [System.SerializableAttribute()]
    public partial class ZelenaPostaResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SlotIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SlotId {
            get {
                return this.SlotIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SlotIdField, value) != true)) {
                    this.SlotIdField = value;
                    this.RaisePropertyChanged("SlotId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailingItem", Namespace="http://www.corageo.sk/schemas/CommIss")]
    [System.SerializableAttribute()]
    public partial class MailingItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CisloKonaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDRegZaznamuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[][] filesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.Recipient recipientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.Sender senderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CisloKonania {
            get {
                return this.CisloKonaniaField;
            }
            set {
                if ((object.ReferenceEquals(this.CisloKonaniaField, value) != true)) {
                    this.CisloKonaniaField = value;
                    this.RaisePropertyChanged("CisloKonania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDRegZaznamu {
            get {
                return this.IDRegZaznamuField;
            }
            set {
                if ((object.ReferenceEquals(this.IDRegZaznamuField, value) != true)) {
                    this.IDRegZaznamuField = value;
                    this.RaisePropertyChanged("IDRegZaznamu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[][] files {
            get {
                return this.filesField;
            }
            set {
                if ((object.ReferenceEquals(this.filesField, value) != true)) {
                    this.filesField = value;
                    this.RaisePropertyChanged("files");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string product {
            get {
                return this.productField;
            }
            set {
                if ((object.ReferenceEquals(this.productField, value) != true)) {
                    this.productField = value;
                    this.RaisePropertyChanged("product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.Recipient recipient {
            get {
                return this.recipientField;
            }
            set {
                if ((object.ReferenceEquals(this.recipientField, value) != true)) {
                    this.recipientField = value;
                    this.RaisePropertyChanged("recipient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.Sender sender {
            get {
                return this.senderField;
            }
            set {
                if ((object.ReferenceEquals(this.senderField, value) != true)) {
                    this.senderField = value;
                    this.RaisePropertyChanged("sender");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZelenaPostaStatus.MailingStates", Namespace="http://schemas.datacontract.org/2004/07/Cora.CommIss.Iss.ZelenaPosta")]
    public enum ZelenaPostaStatusMailingStates : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Paused = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ignored = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProviderRequested = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProviderReceived = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProviderPrinted = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProviderSent = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProviderResent = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProviderDelivered = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CgSent = 99,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CgError = -1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="productInfo", Namespace="http://schemas.datacontract.org/2004/07/Cora.CommIss.Iss.ZelenaPostaAPI2ProductRe" +
        "quireClient")]
    [System.SerializableAttribute()]
    public partial class productInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.ComponentModel.PropertyChangedEventHandler PropertyChanged1Field;
        
        private string codeFieldField;
        
        private string correspondenceFieldField;
        
        private string[] countriesFieldField;
        
        private string envelopeCodeFieldField;
        
        private string envelopeFieldField;
        
        private bool isDuplexFieldField;
        
        private bool isRegisteredPostFieldField;
        
        private int pagesPerMailingFieldField;
        
        private bool pagesPerMailingFieldSpecifiedField;
        
        private string paperFieldField;
        
        private string printingFieldField;
        
        private string propertiesFieldField;
        
        private string[] regionsFieldField;
        
        private string titleFieldField;
        
        private int usageLeftFieldField;
        
        private bool usageLeftFieldSpecifiedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="PropertyChanged", IsRequired=true)]
        public System.ComponentModel.PropertyChangedEventHandler PropertyChanged1 {
            get {
                return this.PropertyChanged1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyChanged1Field, value) != true)) {
                    this.PropertyChanged1Field = value;
                    this.RaisePropertyChanged("PropertyChanged1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codeField {
            get {
                return this.codeFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.codeFieldField, value) != true)) {
                    this.codeFieldField = value;
                    this.RaisePropertyChanged("codeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string correspondenceField {
            get {
                return this.correspondenceFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.correspondenceFieldField, value) != true)) {
                    this.correspondenceFieldField = value;
                    this.RaisePropertyChanged("correspondenceField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string[] countriesField {
            get {
                return this.countriesFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.countriesFieldField, value) != true)) {
                    this.countriesFieldField = value;
                    this.RaisePropertyChanged("countriesField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string envelopeCodeField {
            get {
                return this.envelopeCodeFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.envelopeCodeFieldField, value) != true)) {
                    this.envelopeCodeFieldField = value;
                    this.RaisePropertyChanged("envelopeCodeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string envelopeField {
            get {
                return this.envelopeFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.envelopeFieldField, value) != true)) {
                    this.envelopeFieldField = value;
                    this.RaisePropertyChanged("envelopeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool isDuplexField {
            get {
                return this.isDuplexFieldField;
            }
            set {
                if ((this.isDuplexFieldField.Equals(value) != true)) {
                    this.isDuplexFieldField = value;
                    this.RaisePropertyChanged("isDuplexField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool isRegisteredPostField {
            get {
                return this.isRegisteredPostFieldField;
            }
            set {
                if ((this.isRegisteredPostFieldField.Equals(value) != true)) {
                    this.isRegisteredPostFieldField = value;
                    this.RaisePropertyChanged("isRegisteredPostField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int pagesPerMailingField {
            get {
                return this.pagesPerMailingFieldField;
            }
            set {
                if ((this.pagesPerMailingFieldField.Equals(value) != true)) {
                    this.pagesPerMailingFieldField = value;
                    this.RaisePropertyChanged("pagesPerMailingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool pagesPerMailingFieldSpecified {
            get {
                return this.pagesPerMailingFieldSpecifiedField;
            }
            set {
                if ((this.pagesPerMailingFieldSpecifiedField.Equals(value) != true)) {
                    this.pagesPerMailingFieldSpecifiedField = value;
                    this.RaisePropertyChanged("pagesPerMailingFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string paperField {
            get {
                return this.paperFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.paperFieldField, value) != true)) {
                    this.paperFieldField = value;
                    this.RaisePropertyChanged("paperField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string printingField {
            get {
                return this.printingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.printingFieldField, value) != true)) {
                    this.printingFieldField = value;
                    this.RaisePropertyChanged("printingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string propertiesField {
            get {
                return this.propertiesFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.propertiesFieldField, value) != true)) {
                    this.propertiesFieldField = value;
                    this.RaisePropertyChanged("propertiesField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string[] regionsField {
            get {
                return this.regionsFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.regionsFieldField, value) != true)) {
                    this.regionsFieldField = value;
                    this.RaisePropertyChanged("regionsField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string titleField {
            get {
                return this.titleFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.titleFieldField, value) != true)) {
                    this.titleFieldField = value;
                    this.RaisePropertyChanged("titleField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int usageLeftField {
            get {
                return this.usageLeftFieldField;
            }
            set {
                if ((this.usageLeftFieldField.Equals(value) != true)) {
                    this.usageLeftFieldField = value;
                    this.RaisePropertyChanged("usageLeftField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool usageLeftFieldSpecified {
            get {
                return this.usageLeftFieldSpecifiedField;
            }
            set {
                if ((this.usageLeftFieldSpecifiedField.Equals(value) != true)) {
                    this.usageLeftFieldSpecifiedField = value;
                    this.RaisePropertyChanged("usageLeftFieldSpecified");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.corageo.sk/schemas/CommIss", ConfigurationName="ZelenaPostaProvidePrivateClient.IZelenaPostaProvidePrivate")]
    public interface IZelenaPostaProvidePrivate {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/Send", ReplyAction="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/SendResponse")]
        Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.ZelenaPostaResponse Send(string title, string product, byte[] file, Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.Recipient recipient, Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.Sender sender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/Send", ReplyAction="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/SendResponse")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.ZelenaPostaResponse> SendAsync(string title, string product, byte[] file, Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.Recipient recipient, Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.Sender sender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/Send2", ReplyAction="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/Send2Response")]
        Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.ZelenaPostaResponse Send2(string title, string product, byte[][] files, Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.Recipient recipient, Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.Sender sender, string IDRegZaznamu, string CisloKonania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/Send2", ReplyAction="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/Send2Response")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.ZelenaPostaResponse> Send2Async(string title, string product, byte[][] files, Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.Recipient recipient, Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.Sender sender, string IDRegZaznamu, string CisloKonania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/SendHromadne", ReplyAction="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/SendHromadneResp" +
            "onse")]
        Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.ZelenaPostaResponse SendHromadne(string title, Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.MailingItem[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/SendHromadne", ReplyAction="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/SendHromadneResp" +
            "onse")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.ZelenaPostaResponse> SendHromadneAsync(string title, Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.MailingItem[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/GetMailingsStatu" +
            "s", ReplyAction="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/GetMailingsStatu" +
            "sResponse")]
        void GetMailingsStatus(string slotId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/GetMailingsStatu" +
            "s", ReplyAction="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/GetMailingsStatu" +
            "sResponse")]
        System.Threading.Tasks.Task GetMailingsStatusAsync(string slotId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/CancelMailings", ReplyAction="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/CancelMailingsRe" +
            "sponse")]
        void CancelMailings(string slotId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/CancelMailings", ReplyAction="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/CancelMailingsRe" +
            "sponse")]
        System.Threading.Tasks.Task CancelMailingsAsync(string slotId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/GetStatus", ReplyAction="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/GetStatusRespons" +
            "e")]
        Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.ZelenaPostaStatusMailingStates GetStatus(string slotId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/GetStatus", ReplyAction="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/GetStatusRespons" +
            "e")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.ZelenaPostaStatusMailingStates> GetStatusAsync(string slotId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/GetProducts", ReplyAction="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/GetProductsRespo" +
            "nse")]
        Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.productInfo[] GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/GetProducts", ReplyAction="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/GetProductsRespo" +
            "nse")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.productInfo[]> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/SendCompat", ReplyAction="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/SendCompatRespon" +
            "se")]
        byte[] SendCompat(string title, string product, string file, string recName, string recStreet, string recCity, string recZip, string recCountry, string sndName, string sndStreet, string sndCity, string sndZip, string sndCountry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/SendCompat", ReplyAction="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/SendCompatRespon" +
            "se")]
        System.Threading.Tasks.Task<byte[]> SendCompatAsync(string title, string product, string file, string recName, string recStreet, string recCity, string recZip, string recCountry, string sndName, string sndStreet, string sndCity, string sndZip, string sndCountry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/Send2Compat", ReplyAction="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/Send2CompatRespo" +
            "nse")]
        byte[] Send2Compat(string title, string product, string file, string recName, string recStreet, string recCity, string recZip, string recCountry, string sndName, string sndStreet, string sndCity, string sndZip, string sndCountry, string IDRegZaznamu, string CisloKonania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/Send2Compat", ReplyAction="http://www.corageo.sk/schemas/CommIss/IZelenaPostaProvidePrivate/Send2CompatRespo" +
            "nse")]
        System.Threading.Tasks.Task<byte[]> Send2CompatAsync(string title, string product, string file, string recName, string recStreet, string recCity, string recZip, string recCountry, string sndName, string sndStreet, string sndCity, string sndZip, string sndCountry, string IDRegZaznamu, string CisloKonania);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZelenaPostaProvidePrivateChannel : Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.IZelenaPostaProvidePrivate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZelenaPostaProvidePrivateClient : System.ServiceModel.ClientBase<Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.IZelenaPostaProvidePrivate>, Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.IZelenaPostaProvidePrivate {
        
        public ZelenaPostaProvidePrivateClient() {
        }
        
        public ZelenaPostaProvidePrivateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZelenaPostaProvidePrivateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZelenaPostaProvidePrivateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZelenaPostaProvidePrivateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.ZelenaPostaResponse Send(string title, string product, byte[] file, Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.Recipient recipient, Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.Sender sender) {
            return base.Channel.Send(title, product, file, recipient, sender);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.ZelenaPostaResponse> SendAsync(string title, string product, byte[] file, Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.Recipient recipient, Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.Sender sender) {
            return base.Channel.SendAsync(title, product, file, recipient, sender);
        }
        
        public Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.ZelenaPostaResponse Send2(string title, string product, byte[][] files, Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.Recipient recipient, Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.Sender sender, string IDRegZaznamu, string CisloKonania) {
            return base.Channel.Send2(title, product, files, recipient, sender, IDRegZaznamu, CisloKonania);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.ZelenaPostaResponse> Send2Async(string title, string product, byte[][] files, Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.Recipient recipient, Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.Sender sender, string IDRegZaznamu, string CisloKonania) {
            return base.Channel.Send2Async(title, product, files, recipient, sender, IDRegZaznamu, CisloKonania);
        }
        
        public Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.ZelenaPostaResponse SendHromadne(string title, Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.MailingItem[] items) {
            return base.Channel.SendHromadne(title, items);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.ZelenaPostaResponse> SendHromadneAsync(string title, Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.MailingItem[] items) {
            return base.Channel.SendHromadneAsync(title, items);
        }
        
        public void GetMailingsStatus(string slotId) {
            base.Channel.GetMailingsStatus(slotId);
        }
        
        public System.Threading.Tasks.Task GetMailingsStatusAsync(string slotId) {
            return base.Channel.GetMailingsStatusAsync(slotId);
        }
        
        public void CancelMailings(string slotId) {
            base.Channel.CancelMailings(slotId);
        }
        
        public System.Threading.Tasks.Task CancelMailingsAsync(string slotId) {
            return base.Channel.CancelMailingsAsync(slotId);
        }
        
        public Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.ZelenaPostaStatusMailingStates GetStatus(string slotId) {
            return base.Channel.GetStatus(slotId);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.ZelenaPostaStatusMailingStates> GetStatusAsync(string slotId) {
            return base.Channel.GetStatusAsync(slotId);
        }
        
        public Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.productInfo[] GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaProvidePrivateClient.productInfo[]> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public byte[] SendCompat(string title, string product, string file, string recName, string recStreet, string recCity, string recZip, string recCountry, string sndName, string sndStreet, string sndCity, string sndZip, string sndCountry) {
            return base.Channel.SendCompat(title, product, file, recName, recStreet, recCity, recZip, recCountry, sndName, sndStreet, sndCity, sndZip, sndCountry);
        }
        
        public System.Threading.Tasks.Task<byte[]> SendCompatAsync(string title, string product, string file, string recName, string recStreet, string recCity, string recZip, string recCountry, string sndName, string sndStreet, string sndCity, string sndZip, string sndCountry) {
            return base.Channel.SendCompatAsync(title, product, file, recName, recStreet, recCity, recZip, recCountry, sndName, sndStreet, sndCity, sndZip, sndCountry);
        }
        
        public byte[] Send2Compat(string title, string product, string file, string recName, string recStreet, string recCity, string recZip, string recCountry, string sndName, string sndStreet, string sndCity, string sndZip, string sndCountry, string IDRegZaznamu, string CisloKonania) {
            return base.Channel.Send2Compat(title, product, file, recName, recStreet, recCity, recZip, recCountry, sndName, sndStreet, sndCity, sndZip, sndCountry, IDRegZaznamu, CisloKonania);
        }
        
        public System.Threading.Tasks.Task<byte[]> Send2CompatAsync(string title, string product, string file, string recName, string recStreet, string recCity, string recZip, string recCountry, string sndName, string sndStreet, string sndCity, string sndZip, string sndCountry, string IDRegZaznamu, string CisloKonania) {
            return base.Channel.Send2CompatAsync(title, product, file, recName, recStreet, recCity, recZip, recCountry, sndName, sndStreet, sndCity, sndZip, sndCountry, IDRegZaznamu, CisloKonania);
        }
    }
}
