// Generated by NATeC ClassGenerator v. 4.2.2014.502
// Source model: D:\svnroot\proj\Portal_ISS\extra\2017.3.1\Analyzy a davky\Zelena posta\ZP.PDM
// Please do not edit this file - for custom additions to this class use a separate *$cust.cs file instead.
// Class Options: NOARCHIVE

using System;
using System.Data;
using Cora.Data.DBProvider;
using Cora.Natec.Base;
using System.Collections.Generic;
using Cora.Global.Session;

namespace Cora.CommIss.Iss
{
	/// <summary>
	/// Stavy zelenej pošty (business trieda).
	/// </summary>
	[Serializable]
	public partial class CdoZPO_MAILING_STATE : clsDataObj
	{
		#region Properties

		/// <summary>
		/// Vráti alebo nastaví primárny kľúč.
		/// </summary>
		/// <value>Primárny kľúč.</value>
		public override long iPK
		{
			get
			{
				return _col_I_MAILING_STATE;
			}
			set
			{
				_col_I_MAILING_STATE = (int)value;
			}
		}

		/// <summary>
		/// Vráti alebo nastaví ID.
		/// </summary>
		/// <value>ID.</value>
		public int col_I_MAILING_STATE
		{
			get
			{
				return _col_I_MAILING_STATE;
			}
			set
			{
				_col_I_MAILING_STATE = value;
			}
		}

		/// <summary>
		/// Vráti alebo nastaví ID zásielky.
		/// </summary>
		/// <value>ID zásielky.</value>
		public int col_I_MAILING
		{
			get
			{
				return _col_I_MAILING;
			}
			set
			{
				_col_I_MAILING = value;
			}
		}

		/// <summary>
		/// Vráti alebo nastaví ID stavu zásielky.
		/// </summary>
		/// <value>ID stavu zásielky.</value>
		public int col_I_STATE
		{
			get
			{
				return _col_I_STATE;
			}
			set
			{
				_col_I_STATE = value;
			}
		}

		/// <summary>
		/// Vráti alebo nastaví Dátum aktualizácie.
		/// </summary>
		/// <value>Dátum aktualizácie.</value>
		public DateTime col_DATE_UPDATED
		{
			get
			{
				return _col_DATE_UPDATED;
			}
			set
			{
				_col_DATE_UPDATED = value;
			}
		}

		#endregion

		#region Public Methods

		/// <summary>
		/// Vráti referencovaný dátový objekt (Zásielky zelenej pošty) podľa hodnoty cudzieho kľúča <see cref="col_I_MAILING"/>.
		/// </summary>
		/// <param name="conn">Voliteľné dátové spojenie (napr. kvôli transakčnosti).</param>
		/// <returns>Dátový objekt s ID rovným hodnote <see cref="col_I_MAILING"/>.</returns>
		public CdoZPO_MAILING GetZPO_MAILING_col_I_MAILING(IDbConnection conn = null)
		{
			return FactoryFactory.GetSFactory<CdoZPO_MAILING>().getByPK(conn, col_I_MAILING, this.Identity);
		}

		/// <summary>
		/// Vráti referencovaný dátový objekt (Číselník stavov zelenej pošty) podľa hodnoty cudzieho kľúča <see cref="col_I_STATE"/>.
		/// </summary>
		/// <param name="conn">Voliteľné dátové spojenie (napr. kvôli transakčnosti).</param>
		/// <returns>Dátový objekt s ID rovným hodnote <see cref="col_I_STATE"/>.</returns>
		public CdoZPO_C_STATE GetZPO_C_STATE_col_I_STATE(IDbConnection conn = null)
		{
			return FactoryFactory.GetSFactory<CdoZPO_C_STATE>().getByPK(conn, col_I_STATE, this.Identity);
		}

		/// <summary>
		/// Načíta atribúty inštancie z dátového reader-a.
		/// </summary>
		/// <param name="oResult">Dátový reader. Názvy stĺpcov v reader-i musia zodpovedať názvom stĺpcov tabuľky.</param>
		/// <returns>Vždy <c>true</c>.</returns>
		public override void fillAttributes(IDataReader oResult)
		{
			_setAttrib(out _col_I_MAILING_STATE, oResult["I_MAILING_STATE"]);
			_setAttrib(out _col_I_MAILING, oResult["I_MAILING"]);
			_setAttrib(out _col_I_STATE, oResult["I_STATE"]);
			_setAttrib(out _col_DATE_UPDATED, oResult["DATE_UPDATED"]);
		}

		/// <summary>
		/// Inicializuje inštanciu.
		/// </summary>
		public override bool Init()
		{
			base._classID = 316003000;
			sTabMain = "ZPO_MAILING_STATE";
			sTabs = "ZPO_MAILING_STATE";
			sColPK = "I_MAILING_STATE";
			sCols = "I_MAILING_STATE,I_MAILING,I_STATE,DATE_UPDATED";
			return true;
		}

		#endregion

		#region Protected Methods

		/// <summary>
		/// Pridá do DB príkazu viazaný parameter vytvorený z hodnoty primárneho kľúča.
		/// </summary>
		/// <param name="myCommand">Databázový príkaz, kam sa pridá vytvorený parameter.</param>
		/// <returns>Vytvorený a do príkazu pridaný viazaný parameter.</returns>
		protected override CoraParameter AddPkParam(CoraCommand myCommand)
		{
			CoraParameter parameterI_MAILING_STATE = new CoraParameter("@I_MAILING_STATE", DbType.Int32);
			parameterI_MAILING_STATE.Value = col_I_MAILING_STATE;
			myCommand.Parameters.Add(parameterI_MAILING_STATE);
			return parameterI_MAILING_STATE;
		}

		/// <summary>
		/// Pridá do DB príkazu viazané parametre vytvorené z hodnôt nie-primárnych stĺpcov.
		/// </summary>
		/// <param name="myCommand">Databázový príkaz, kam sa pridaju vytvorené parametre.</param>
		protected override void AddParams(CoraCommand myCommand)
		{
			CoraParameter parameterI_MAILING = new CoraParameter("@I_MAILING", DbType.Int32);
			parameterI_MAILING.Value = col_I_MAILING;
			myCommand.Parameters.Add(parameterI_MAILING);
			CoraParameter parameterI_STATE = new CoraParameter("@I_STATE", DbType.Int32);
			parameterI_STATE.Value = col_I_STATE;
			myCommand.Parameters.Add(parameterI_STATE);
			CoraParameter parameterDATE_UPDATED = new CoraParameter("@DATE_UPDATED", DbType.DateTime);
			parameterDATE_UPDATED.Value = col_DATE_UPDATED;
			myCommand.Parameters.Add(parameterDATE_UPDATED);
		}

		#endregion

		private int _col_I_MAILING_STATE;
		private int _col_I_MAILING;
		private int _col_I_STATE;
		private DateTime _col_DATE_UPDATED;
	}

	/// <summary>
	/// Trieda extension metód pre získavanie zoznamov dátových objektov podľa reverzných kľúčov.
	/// </summary>
	public static partial class ReverseKeyExtensions
	{
		#region I_MAILING

		/// <summary>
		/// Vráti všetky objekty dátového typu <see cref="Cora.CommIss.Iss.CdoZPO_MAILING_STATE"/>,
		/// ktoré obsahujú referenciu na objekt dátového typu <see cref="Cora.CommIss.Iss.CdoZPO_MAILING"/>
		/// s hodnotou cudzieho kľúča <see cref="Cora.CommIss.Iss.CdoZPO_MAILING_STATE.col_I_MAILING" />.
		/// </summary>
		/// <param name="cdoZPO_MAILING">Referencovaný objekt.</param>
		/// <param name="conn">Voliteľné dátové spojenie (napr. kvôli transakčnosti).</param>
		/// <param name="order">Výraz do ORDER BY.</param>
		/// <returns>Kolekcia objektov dátového typu<see cref="Cora.CommIss.Iss.CdoZPO_MAILING_STATE"/>.</returns>
		/// <exception cref="ArgumentNullException">Ak <paramref name="cdoZPO_MAILING"/> je <c>null</c>.</exception>
		public static IEnumerable<Cora.CommIss.Iss.CdoZPO_MAILING_STATE> GetAllCdoZPO_MAILING_STATE_col_I_MAILING(
			this Cora.CommIss.Iss.CdoZPO_MAILING cdoZPO_MAILING, IDbConnection conn = null, string order = null)
		{
			if ( null == cdoZPO_MAILING )
				throw new ArgumentNullException("cdoZPO_MAILING");

			return GetAllCdoZPO_MAILING_STATE_col_I_MAILING(cdoZPO_MAILING.col_I_MAILING, conn, order, cdoZPO_MAILING.Identity);
		}

		/// <summary>
		/// Vráti všetky objekty dátového typu <see cref="Cora.CommIss.Iss.CdoZPO_MAILING_STATE"/>,
		/// ktoré obsahujú referenciu na objekt dátového typu <see cref="Cora.CommIss.Iss.CdoZPO_MAILING"/>
		/// s hodnotou cudzieho kľúča <see cref="Cora.CommIss.Iss.CdoZPO_MAILING_STATE.col_I_MAILING" />.
		/// </summary>
		/// <param name="col_I_MAILING">Primárny kľúč referencovaného objektu.</param>
		/// <param name="conn">Voliteľné dátové spojenie (napr. kvôli transakčnosti).</param>
		/// <param name="order">Výraz do ORDER BY.</param>
		/// <param name="identity">Identita používateľa.</param>
		/// <returns>Kolekcia objektov dátového typu<see cref="Cora.CommIss.Iss.CdoZPO_MAILING_STATE"/>.</returns>
		public static IEnumerable<Cora.CommIss.Iss.CdoZPO_MAILING_STATE> GetAllCdoZPO_MAILING_STATE_col_I_MAILING(
			 int col_I_MAILING, IDbConnection conn = null, string order = null, IIdentity identity = null)
		{
			return FactoryFactory.GetSFactory<Cora.CommIss.Iss.CdoZPO_MAILING_STATE>().
				GetByCondParam(conn, "I_MAILING = <paramBind>P0</paramBind>",
				new object[] { col_I_MAILING }, order, identity);
		}

		#endregion

		#region I_STATE

		/// <summary>
		/// Vráti všetky objekty dátového typu <see cref="Cora.CommIss.Iss.CdoZPO_MAILING_STATE"/>,
		/// ktoré obsahujú referenciu na objekt dátového typu <see cref="Cora.CommIss.Iss.CdoZPO_C_STATE"/>
		/// s hodnotou cudzieho kľúča <see cref="Cora.CommIss.Iss.CdoZPO_MAILING_STATE.col_I_STATE" />.
		/// </summary>
		/// <param name="cdoZPO_C_STATE">Referencovaný objekt.</param>
		/// <param name="conn">Voliteľné dátové spojenie (napr. kvôli transakčnosti).</param>
		/// <param name="order">Výraz do ORDER BY.</param>
		/// <returns>Kolekcia objektov dátového typu<see cref="Cora.CommIss.Iss.CdoZPO_MAILING_STATE"/>.</returns>
		/// <exception cref="ArgumentNullException">Ak <paramref name="cdoZPO_C_STATE"/> je <c>null</c>.</exception>
		public static IEnumerable<Cora.CommIss.Iss.CdoZPO_MAILING_STATE> GetAllCdoZPO_MAILING_STATE_col_I_STATE(
			this Cora.CommIss.Iss.CdoZPO_C_STATE cdoZPO_C_STATE, IDbConnection conn = null, string order = null)
		{
			if ( null == cdoZPO_C_STATE )
				throw new ArgumentNullException("cdoZPO_C_STATE");

			return GetAllCdoZPO_MAILING_STATE_col_I_STATE(cdoZPO_C_STATE.col_I_STATE, conn, order, cdoZPO_C_STATE.Identity);
		}

		/// <summary>
		/// Vráti všetky objekty dátového typu <see cref="Cora.CommIss.Iss.CdoZPO_MAILING_STATE"/>,
		/// ktoré obsahujú referenciu na objekt dátového typu <see cref="Cora.CommIss.Iss.CdoZPO_C_STATE"/>
		/// s hodnotou cudzieho kľúča <see cref="Cora.CommIss.Iss.CdoZPO_MAILING_STATE.col_I_STATE" />.
		/// </summary>
		/// <param name="col_I_STATE">Primárny kľúč referencovaného objektu.</param>
		/// <param name="conn">Voliteľné dátové spojenie (napr. kvôli transakčnosti).</param>
		/// <param name="order">Výraz do ORDER BY.</param>
		/// <param name="identity">Identita používateľa.</param>
		/// <returns>Kolekcia objektov dátového typu<see cref="Cora.CommIss.Iss.CdoZPO_MAILING_STATE"/>.</returns>
		public static IEnumerable<Cora.CommIss.Iss.CdoZPO_MAILING_STATE> GetAllCdoZPO_MAILING_STATE_col_I_STATE(
			 int col_I_STATE, IDbConnection conn = null, string order = null, IIdentity identity = null)
		{
			return FactoryFactory.GetSFactory<Cora.CommIss.Iss.CdoZPO_MAILING_STATE>().
				GetByCondParam(conn, "I_STATE = <paramBind>P0</paramBind>",
				new object[] { col_I_STATE }, order, identity);
		}

		#endregion


	}
}