// Generated by NATeC ClassGenerator v. 4.2.2014.502
// Source model: D:\svnroot\proj\Portal_ISS\extra\2017.3.1\Analyzy a davky\Zelena posta\ZP.PDM
// Please do not edit this file - for custom additions to this class use a separate *$cust.cs file instead.
// Class Options: NOARCHIVE

using System;
using System.Runtime.Serialization;
using Cora.Natec.Base;

namespace Cora.CommIss.Iss
{
	/// <summary>
	/// Transfer trieda pre <see cref="CdoZPO_MAILING_STATE"/>.
	/// </summary>
	[Serializable]
	[DataContract(Namespace="http://www.corageo.sk/")]
	public partial class CtoZPO_MAILING_STATE
	{
#pragma warning disable 1591
		public long iPK
		{
			get { return I_MAILING_STATE; }
		}

		[DataMember]
		public int I_MAILING_STATE { get; set; }
		[DataMember]
		public int I_MAILING { get; set; }
		[DataMember]
		public int I_STATE { get; set; }
		[DataMember]
		public DateTime DATE_UPDATED { get; set; }
#pragma warning restore 1591
	}

	/// <summary>
	/// Trieda pre konverziu medzi <see cref="CdoZPO_MAILING_STATE"/> a <see cref="CtoZPO_MAILING_STATE"/>.
	/// </summary>
	public static class CtoZPO_MAILING_STATEExtensions
	{
		/// <summary>
		/// Konvertuje business objekt na transfer objekt.
		/// </summary>
		/// <param name="cdo">Business objekt.</param>
		/// <value>Transfer objekt, alebo <c>null</c> ak je business objekt <c>null</c>.</value>
		public static CtoZPO_MAILING_STATE ToDto(this CdoZPO_MAILING_STATE cdo)
		{
			if ( null == cdo )
				return null;

			return new CtoZPO_MAILING_STATE()
			{
				I_MAILING_STATE = cdo.col_I_MAILING_STATE,
				I_MAILING = cdo.col_I_MAILING,
				I_STATE = cdo.col_I_STATE,
				DATE_UPDATED = cdo.col_DATE_UPDATED,
			};
		}

		/// <summary>
		/// Konvertuje transfer objekt na business objekt.
		/// </summary>
		/// <param name="dto">Transfer objekt.</param>
		/// <value>Business objekt, alebo <c>null</c> ak je transfer objekt <c>null</c>.</value>
		public static CdoZPO_MAILING_STATE ToCdo(this CtoZPO_MAILING_STATE dto)
		{
			if ( null == dto )
				return null;

			CdoZPO_MAILING_STATE ret = FactoryFactory.GetSFactory<CdoZPO_MAILING_STATE>().GetNew();
			ret.LoadDto(dto);
			return ret;
		}

		/// <summary>
		/// Nahrá dáta z transfer objektu do business objektu.
		/// </summary>
		/// <param name="cdo">Business objekt.</param>
		/// <param name="dto">Transfer objekt.</param>
		public static void LoadDto(this CdoZPO_MAILING_STATE cdo, CtoZPO_MAILING_STATE dto)
		{
			cdo.col_I_MAILING_STATE = dto.I_MAILING_STATE;
			cdo.col_I_MAILING = dto.I_MAILING;
			cdo.col_I_STATE = dto.I_STATE;
			cdo.col_DATE_UPDATED = dto.DATE_UPDATED;
		}
	}
}