//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.zelenaposta.sk/product", ConfigurationName="ZelenaPostaAPI2ProductRequireClient.ProductService")]
    public interface ProductService {
        
        // CODEGEN: Generating message contract since the operation getEnums is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getEnumsResponse1 getEnums(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getEnumsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getEnumsResponse1> getEnumsAsync(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getEnumsRequest1 request);
        
        // CODEGEN: Generating message contract since the operation computePrice is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.computePriceResponse computePrice(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.computePriceRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.computePriceResponse> computePriceAsync(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.computePriceRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getProducts is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getProductsResponse1 getProducts(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getProductsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getProductsResponse1> getProductsAsync(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getProductsRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.zelenaposta.sk/product")]
    public partial class getEnumsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.zelenaposta.sk/product")]
    public partial class productInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string titleField;
        
        private string correspondenceField;
        
        private string envelopeField;
        
        private string envelopeCodeField;
        
        private string printingField;
        
        private int usageLeftField;
        
        private bool usageLeftFieldSpecified;
        
        private int pagesPerMailingField;
        
        private bool pagesPerMailingFieldSpecified;
        
        private bool isDuplexField;
        
        private bool isRegisteredPostField;
        
        private string[] countriesField;
        
        private string[] regionsField;
        
        private string propertiesField;
        
        private string paperField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string correspondence {
            get {
                return this.correspondenceField;
            }
            set {
                this.correspondenceField = value;
                this.RaisePropertyChanged("correspondence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string envelope {
            get {
                return this.envelopeField;
            }
            set {
                this.envelopeField = value;
                this.RaisePropertyChanged("envelope");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string envelopeCode {
            get {
                return this.envelopeCodeField;
            }
            set {
                this.envelopeCodeField = value;
                this.RaisePropertyChanged("envelopeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string printing {
            get {
                return this.printingField;
            }
            set {
                this.printingField = value;
                this.RaisePropertyChanged("printing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int usageLeft {
            get {
                return this.usageLeftField;
            }
            set {
                this.usageLeftField = value;
                this.RaisePropertyChanged("usageLeft");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usageLeftSpecified {
            get {
                return this.usageLeftFieldSpecified;
            }
            set {
                this.usageLeftFieldSpecified = value;
                this.RaisePropertyChanged("usageLeftSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int pagesPerMailing {
            get {
                return this.pagesPerMailingField;
            }
            set {
                this.pagesPerMailingField = value;
                this.RaisePropertyChanged("pagesPerMailing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pagesPerMailingSpecified {
            get {
                return this.pagesPerMailingFieldSpecified;
            }
            set {
                this.pagesPerMailingFieldSpecified = value;
                this.RaisePropertyChanged("pagesPerMailingSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool isDuplex {
            get {
                return this.isDuplexField;
            }
            set {
                this.isDuplexField = value;
                this.RaisePropertyChanged("isDuplex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool isRegisteredPost {
            get {
                return this.isRegisteredPostField;
            }
            set {
                this.isRegisteredPostField = value;
                this.RaisePropertyChanged("isRegisteredPost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("code", IsNullable=false)]
        public string[] countries {
            get {
                return this.countriesField;
            }
            set {
                this.countriesField = value;
                this.RaisePropertyChanged("countries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("code", IsNullable=false)]
        public string[] regions {
            get {
                return this.regionsField;
            }
            set {
                this.regionsField = value;
                this.RaisePropertyChanged("regions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
                this.RaisePropertyChanged("properties");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string paper {
            get {
                return this.paperField;
            }
            set {
                this.paperField = value;
                this.RaisePropertyChanged("paper");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.zelenaposta.sk/product")]
    public partial class getProductsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private productInfo[] productsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("product", IsNullable=false)]
        public productInfo[] products {
            get {
                return this.productsField;
            }
            set {
                this.productsField = value;
                this.RaisePropertyChanged("products");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.zelenaposta.sk/product")]
    public partial class getProductsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool duplexField;
        
        private bool duplexFieldSpecified;
        
        private bool backpageField;
        
        private bool backpageFieldSpecified;
        
        private bool electronicField;
        
        private bool electronicFieldSpecified;
        
        private int pagesField;
        
        private bool pagesFieldSpecified;
        
        private string correspondenceField;
        
        private string envelopeField;
        
        private string envelopeCodeField;
        
        private string printingField;
        
        private string paperField;
        
        private string countryCodeField;
        
        private string onBehalfOfField;
        
        /// <remarks/>
        public bool duplex {
            get {
                return this.duplexField;
            }
            set {
                this.duplexField = value;
                this.RaisePropertyChanged("duplex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool duplexSpecified {
            get {
                return this.duplexFieldSpecified;
            }
            set {
                this.duplexFieldSpecified = value;
                this.RaisePropertyChanged("duplexSpecified");
            }
        }
        
        /// <remarks/>
        public bool backpage {
            get {
                return this.backpageField;
            }
            set {
                this.backpageField = value;
                this.RaisePropertyChanged("backpage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool backpageSpecified {
            get {
                return this.backpageFieldSpecified;
            }
            set {
                this.backpageFieldSpecified = value;
                this.RaisePropertyChanged("backpageSpecified");
            }
        }
        
        /// <remarks/>
        public bool electronic {
            get {
                return this.electronicField;
            }
            set {
                this.electronicField = value;
                this.RaisePropertyChanged("electronic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool electronicSpecified {
            get {
                return this.electronicFieldSpecified;
            }
            set {
                this.electronicFieldSpecified = value;
                this.RaisePropertyChanged("electronicSpecified");
            }
        }
        
        /// <remarks/>
        public int pages {
            get {
                return this.pagesField;
            }
            set {
                this.pagesField = value;
                this.RaisePropertyChanged("pages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pagesSpecified {
            get {
                return this.pagesFieldSpecified;
            }
            set {
                this.pagesFieldSpecified = value;
                this.RaisePropertyChanged("pagesSpecified");
            }
        }
        
        /// <remarks/>
        public string correspondence {
            get {
                return this.correspondenceField;
            }
            set {
                this.correspondenceField = value;
                this.RaisePropertyChanged("correspondence");
            }
        }
        
        /// <remarks/>
        public string envelope {
            get {
                return this.envelopeField;
            }
            set {
                this.envelopeField = value;
                this.RaisePropertyChanged("envelope");
            }
        }
        
        /// <remarks/>
        public string envelopeCode {
            get {
                return this.envelopeCodeField;
            }
            set {
                this.envelopeCodeField = value;
                this.RaisePropertyChanged("envelopeCode");
            }
        }
        
        /// <remarks/>
        public string printing {
            get {
                return this.printingField;
            }
            set {
                this.printingField = value;
                this.RaisePropertyChanged("printing");
            }
        }
        
        /// <remarks/>
        public string paper {
            get {
                return this.paperField;
            }
            set {
                this.paperField = value;
                this.RaisePropertyChanged("paper");
            }
        }
        
        /// <remarks/>
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("countryCode");
            }
        }
        
        /// <remarks/>
        public string onBehalfOf {
            get {
                return this.onBehalfOfField;
            }
            set {
                this.onBehalfOfField = value;
                this.RaisePropertyChanged("onBehalfOf");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.zelenaposta.sk/product")]
    public partial class computePriceInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal priceField;
        
        private bool priceFieldSpecified;
        
        private decimal priceAndVatField;
        
        private bool priceAndVatFieldSpecified;
        
        private decimal productionPriceField;
        
        private bool productionPriceFieldSpecified;
        
        private decimal productionPriceAndVatField;
        
        private bool productionPriceAndVatFieldSpecified;
        
        private decimal postagePriceField;
        
        private bool postagePriceFieldSpecified;
        
        private decimal postagePriceAndVatField;
        
        private bool postagePriceAndVatFieldSpecified;
        
        /// <remarks/>
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
                this.RaisePropertyChanged("priceSpecified");
            }
        }
        
        /// <remarks/>
        public decimal priceAndVat {
            get {
                return this.priceAndVatField;
            }
            set {
                this.priceAndVatField = value;
                this.RaisePropertyChanged("priceAndVat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceAndVatSpecified {
            get {
                return this.priceAndVatFieldSpecified;
            }
            set {
                this.priceAndVatFieldSpecified = value;
                this.RaisePropertyChanged("priceAndVatSpecified");
            }
        }
        
        /// <remarks/>
        public decimal productionPrice {
            get {
                return this.productionPriceField;
            }
            set {
                this.productionPriceField = value;
                this.RaisePropertyChanged("productionPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productionPriceSpecified {
            get {
                return this.productionPriceFieldSpecified;
            }
            set {
                this.productionPriceFieldSpecified = value;
                this.RaisePropertyChanged("productionPriceSpecified");
            }
        }
        
        /// <remarks/>
        public decimal productionPriceAndVat {
            get {
                return this.productionPriceAndVatField;
            }
            set {
                this.productionPriceAndVatField = value;
                this.RaisePropertyChanged("productionPriceAndVat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productionPriceAndVatSpecified {
            get {
                return this.productionPriceAndVatFieldSpecified;
            }
            set {
                this.productionPriceAndVatFieldSpecified = value;
                this.RaisePropertyChanged("productionPriceAndVatSpecified");
            }
        }
        
        /// <remarks/>
        public decimal postagePrice {
            get {
                return this.postagePriceField;
            }
            set {
                this.postagePriceField = value;
                this.RaisePropertyChanged("postagePrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool postagePriceSpecified {
            get {
                return this.postagePriceFieldSpecified;
            }
            set {
                this.postagePriceFieldSpecified = value;
                this.RaisePropertyChanged("postagePriceSpecified");
            }
        }
        
        /// <remarks/>
        public decimal postagePriceAndVat {
            get {
                return this.postagePriceAndVatField;
            }
            set {
                this.postagePriceAndVatField = value;
                this.RaisePropertyChanged("postagePriceAndVat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool postagePriceAndVatSpecified {
            get {
                return this.postagePriceAndVatFieldSpecified;
            }
            set {
                this.postagePriceAndVatFieldSpecified = value;
                this.RaisePropertyChanged("postagePriceAndVatSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.zelenaposta.sk/product")]
    public partial class computePriceMailing : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string productNameField;
        
        private int pageCountField;
        
        private int[] mailingDocumentsPageCountsField;
        
        /// <remarks/>
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("productName");
            }
        }
        
        /// <remarks/>
        public int pageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
                this.RaisePropertyChanged("pageCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("mailingDocumentPageCount", IsNullable=false)]
        public int[] mailingDocumentsPageCounts {
            get {
                return this.mailingDocumentsPageCountsField;
            }
            set {
                this.mailingDocumentsPageCountsField = value;
                this.RaisePropertyChanged("mailingDocumentsPageCounts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.zelenaposta.sk/product")]
    public partial class computePriceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private computePriceMailing[] mailingsField;
        
        private string deliveryTypeField;
        
        public computePriceRequest() {
            this.deliveryTypeField = "SP";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("mailing", IsNullable=false)]
        public computePriceMailing[] mailings {
            get {
                return this.mailingsField;
            }
            set {
                this.mailingsField = value;
                this.RaisePropertyChanged("mailings");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("SP")]
        public string deliveryType {
            get {
                return this.deliveryTypeField;
            }
            set {
                this.deliveryTypeField = value;
                this.RaisePropertyChanged("deliveryType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.zelenaposta.sk/product")]
    public partial class codeTitleTuple : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.zelenaposta.sk/product")]
    public partial class codeTitleRegisteredTuple : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string titleField;
        
        private bool registeredField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool registered {
            get {
                return this.registeredField;
            }
            set {
                this.registeredField = value;
                this.RaisePropertyChanged("registered");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.zelenaposta.sk/product")]
    public partial class getEnumsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private codeTitleRegisteredTuple[] correspondenceField;
        
        private codeTitleTuple[] envelopeField;
        
        private codeTitleTuple[] printingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public codeTitleRegisteredTuple[] correspondence {
            get {
                return this.correspondenceField;
            }
            set {
                this.correspondenceField = value;
                this.RaisePropertyChanged("correspondence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public codeTitleTuple[] envelope {
            get {
                return this.envelopeField;
            }
            set {
                this.envelopeField = value;
                this.RaisePropertyChanged("envelope");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public codeTitleTuple[] printing {
            get {
                return this.printingField;
            }
            set {
                this.printingField = value;
                this.RaisePropertyChanged("printing");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEnumsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.zelenaposta.sk/product", Order=0)]
        public Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getEnumsRequest getEnumsRequest;
        
        public getEnumsRequest1() {
        }
        
        public getEnumsRequest1(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getEnumsRequest getEnumsRequest) {
            this.getEnumsRequest = getEnumsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEnumsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.zelenaposta.sk/product", Order=0)]
        public Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getEnumsResponse getEnumsResponse;
        
        public getEnumsResponse1() {
        }
        
        public getEnumsResponse1(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getEnumsResponse getEnumsResponse) {
            this.getEnumsResponse = getEnumsResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class computePriceRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.zelenaposta.sk/product", Order=0)]
        public Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.computePriceRequest computePriceRequest;
        
        public computePriceRequest1() {
        }
        
        public computePriceRequest1(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.computePriceRequest computePriceRequest) {
            this.computePriceRequest = computePriceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class computePriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="computePriceResponse", Namespace="http://schemas.zelenaposta.sk/product", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("priceInfo")]
        public Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.computePriceInfo[] computePriceResponse1;
        
        public computePriceResponse() {
        }
        
        public computePriceResponse(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.computePriceInfo[] computePriceResponse1) {
            this.computePriceResponse1 = computePriceResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.zelenaposta.sk/product", Order=0)]
        public Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getProductsRequest getProductsRequest;
        
        public getProductsRequest1() {
        }
        
        public getProductsRequest1(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getProductsRequest getProductsRequest) {
            this.getProductsRequest = getProductsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.zelenaposta.sk/product", Order=0)]
        public Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getProductsResponse getProductsResponse;
        
        public getProductsResponse1() {
        }
        
        public getProductsResponse1(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getProductsResponse getProductsResponse) {
            this.getProductsResponse = getProductsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductServiceChannel : Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.ProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.ProductService>, Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.ProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getEnumsResponse1 Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.ProductService.getEnums(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getEnumsRequest1 request) {
            return base.Channel.getEnums(request);
        }
        
        public Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getEnumsResponse getEnums(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getEnumsRequest getEnumsRequest) {
            Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getEnumsRequest1 inValue = new Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getEnumsRequest1();
            inValue.getEnumsRequest = getEnumsRequest;
            Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getEnumsResponse1 retVal = ((Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.ProductService)(this)).getEnums(inValue);
            return retVal.getEnumsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getEnumsResponse1> Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.ProductService.getEnumsAsync(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getEnumsRequest1 request) {
            return base.Channel.getEnumsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getEnumsResponse1> getEnumsAsync(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getEnumsRequest getEnumsRequest) {
            Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getEnumsRequest1 inValue = new Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getEnumsRequest1();
            inValue.getEnumsRequest = getEnumsRequest;
            return ((Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.ProductService)(this)).getEnumsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.computePriceResponse Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.ProductService.computePrice(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.computePriceRequest1 request) {
            return base.Channel.computePrice(request);
        }
        
        public Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.computePriceInfo[] computePrice(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.computePriceRequest computePriceRequest) {
            Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.computePriceRequest1 inValue = new Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.computePriceRequest1();
            inValue.computePriceRequest = computePriceRequest;
            Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.computePriceResponse retVal = ((Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.ProductService)(this)).computePrice(inValue);
            return retVal.computePriceResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.computePriceResponse> Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.ProductService.computePriceAsync(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.computePriceRequest1 request) {
            return base.Channel.computePriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.computePriceResponse> computePriceAsync(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.computePriceRequest computePriceRequest) {
            Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.computePriceRequest1 inValue = new Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.computePriceRequest1();
            inValue.computePriceRequest = computePriceRequest;
            return ((Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.ProductService)(this)).computePriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getProductsResponse1 Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.ProductService.getProducts(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getProductsRequest1 request) {
            return base.Channel.getProducts(request);
        }
        
        public Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getProductsResponse getProducts(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getProductsRequest getProductsRequest) {
            Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getProductsRequest1 inValue = new Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getProductsRequest1();
            inValue.getProductsRequest = getProductsRequest;
            Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getProductsResponse1 retVal = ((Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.ProductService)(this)).getProducts(inValue);
            return retVal.getProductsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getProductsResponse1> Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.ProductService.getProductsAsync(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getProductsRequest1 request) {
            return base.Channel.getProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getProductsResponse1> getProductsAsync(Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getProductsRequest getProductsRequest) {
            Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getProductsRequest1 inValue = new Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.getProductsRequest1();
            inValue.getProductsRequest = getProductsRequest;
            return ((Cora.CommIss.Iss.ZelenaPostaAPI2ProductRequireClient.ProductService)(this)).getProductsAsync(inValue);
        }
    }
}
